deliveryhero/helm-charts

- README.md
- stable/kube-downscaler/Chart.yaml
- stable/kube-downscaler/LICENSE
- stable/kube-downscaler/README.md
- stable/kube-downscaler/templates/_helpers.tpl
- stable/kube-downscaler/templates/clusterrole.yaml
- stable/kube-downscaler/templates/clusterrolebinding.yaml
- stable/kube-downscaler/templates/deployment.yaml
- stable/kube-downscaler/templates/serviceaccount.yaml
- stable/kube-downscaler/values.yaml
> [stable/kube-downscaler] add chart

- .github/CODEOWNERS
> Adjust codeowners file

- stable/newrelic-controller/.helmignore
- stable/newrelic-controller/Chart.yaml
- stable/newrelic-controller/LICENSE
- stable/newrelic-controller/README.md
- stable/newrelic-controller/templates/NOTES.txt
- stable/newrelic-controller/templates/_helpers.tpl
- stable/newrelic-controller/templates/clusterrole.yaml
- stable/newrelic-controller/templates/clusterrolebinding.yaml
- stable/newrelic-controller/templates/crd.yaml
- stable/newrelic-controller/templates/deployment.yaml
- stable/newrelic-controller/templates/secret.yaml
- stable/newrelic-controller/templates/serviceaccount.yaml
- stable/newrelic-controller/values.yaml
> [stable/newrelic-controller] add chart

- stable/locust/Chart.yaml
- stable/locust/README.md
- stable/locust/templates/NOTES.txt
- stable/locust/templates/_helpers.tpl
- stable/locust/templates/configmap-locust-lib.yaml
- stable/locust/templates/configmap-locust-locustfile.yaml
- stable/locust/templates/master-deployment.yaml
- stable/locust/templates/worker-deployment.yaml
- stable/locust/values.yaml
> [stable/locust] Update locust chart to allow custom load test code in configmaps

- stable/postgres-controller/.helmignore
- stable/postgres-controller/Chart.yaml
- stable/postgres-controller/LICENSE
- stable/postgres-controller/README.md
- stable/postgres-controller/templates/NOTES.txt
- stable/postgres-controller/templates/_helpers.tpl
- stable/postgres-controller/templates/clusterrole.yaml
- stable/postgres-controller/templates/clusterrolebinding.yaml
- stable/postgres-controller/templates/configmap.yaml
- stable/postgres-controller/templates/crd.yaml
- stable/postgres-controller/templates/deployment.yaml
- stable/postgres-controller/templates/serviceaccount.yaml
- stable/postgres-controller/values.yaml
> [stable/postgres-controller] add chart

- stable/k8s-resources/Chart.yaml
- stable/k8s-resources/README.md
- stable/k8s-resources/templates/configmap.yaml
- stable/k8s-resources/templates/custom.yaml
- stable/k8s-resources/templates/hpa.yaml
- stable/k8s-resources/templates/ingress.yaml
- stable/k8s-resources/templates/secret.yaml
- stable/k8s-resources/templates/service.yaml
- stable/k8s-resources/templates/serviceaccount.yaml
> [stable/k8s-resources] allow per resource namespace

- stable/k8s-resources/Chart.yaml
- stable/k8s-resources/README.md
- stable/k8s-resources/ci/ct-values.yaml
- stable/k8s-resources/templates/configmap.yaml
- stable/k8s-resources/templates/custom.yaml
- stable/k8s-resources/templates/hpa.yaml
- stable/k8s-resources/templates/ingress.yaml
- stable/k8s-resources/templates/secret.yaml
- stable/k8s-resources/templates/service.yaml
- stable/k8s-resources/templates/serviceaccount.yaml
- stable/k8s-resources/values.yaml
> [stable/k8s-resources] misc updates and fixes

- stable/hoppscotch/Chart.yaml
- stable/hoppscotch/README.md
- stable/hoppscotch/templates/ingress.yaml
- stable/hoppscotch/templates/service.yaml
Few tweaks for Hoppscotch Chart
> [stable/hoppscotch] Hoppscotch chart update

- README.md
- stable/cloudhealth-collector/.helmignore
- stable/cloudhealth-collector/Chart.yaml
- stable/cloudhealth-collector/README.md
- stable/cloudhealth-collector/ci/ct-values.yaml
- stable/cloudhealth-collector/templates/_helpers.tpl
- stable/cloudhealth-collector/templates/clusterrole.yaml
- stable/cloudhealth-collector/templates/clusterrolebinding.yaml
- stable/cloudhealth-collector/templates/deployment.yaml
- stable/cloudhealth-collector/templates/secret.yaml
- stable/cloudhealth-collector/templates/serviceaccount.yaml
- stable/cloudhealth-collector/values.yaml
> [stable/cloudhealth-collector] add chart

- README.md
- ci/markdown-lint.yaml
- stable/k8s-event-logger/.helmignore
- stable/k8s-event-logger/Chart.yaml
- stable/k8s-event-logger/LICENSE
- stable/k8s-event-logger/README.md
- stable/k8s-event-logger/templates/NOTES.txt
- stable/k8s-event-logger/templates/_helpers.tpl
- stable/k8s-event-logger/templates/clusterrole.yaml
- stable/k8s-event-logger/templates/clusterrolebinding.yaml
- stable/k8s-event-logger/templates/deployment.yaml
- stable/k8s-event-logger/templates/serviceaccount.yaml
- stable/k8s-event-logger/values.yaml
> [stable/k8s-event-logger] add chart

- README.md
> Add a note on how to run chart-testing locally

- stable/locust/Chart.yaml
- stable/locust/README.md
- stable/locust/values.yaml
> [stable/locust] fix values doc in wrong place

- README.md
- stable/node-problem-detector/.helmignore
- stable/node-problem-detector/Chart.yaml
- stable/node-problem-detector/README.md
- stable/node-problem-detector/templates/NOTES.txt
- stable/node-problem-detector/templates/_helpers.tpl
- stable/node-problem-detector/templates/clusterrole.yaml
- stable/node-problem-detector/templates/clusterrolebinding.yaml
- stable/node-problem-detector/templates/custom-config-configmap.yaml
- stable/node-problem-detector/templates/daemonset.yaml
- stable/node-problem-detector/templates/psp-clusterrole.yaml
- stable/node-problem-detector/templates/psp-clusterrolebinding.yaml
- stable/node-problem-detector/templates/psp.yaml
- stable/node-problem-detector/templates/service.yaml
- stable/node-problem-detector/templates/serviceaccount.yaml
- stable/node-problem-detector/templates/servicemonitor.yaml
- stable/node-problem-detector/values.yaml
> [stable/node-problem-detector] add chart

- stable/locust/Chart.yaml
- stable/locust/README.md
- stable/locust/values.yaml
Also add missing tolerations/affinite/nodeselector to values.
> [stable/locust] update to 1.3.0

- stable/prometheus-spot-termination-exporter/Chart.yaml
- stable/prometheus-spot-termination-exporter/README.md
- stable/prometheus-spot-termination-exporter/templates/daemonset.yaml
Added tolerations and affinity to DaemonSet
> [stable/prometheus-spot-termination-exporter] Chart improvements

- stable/locust/Chart.yaml
- stable/locust/README.md
- stable/locust/templates/master-ingress.yaml
- stable/locust/values.yaml
> [stable/locust] small fixes

- stable/node-problem-detector/Chart.yaml
- stable/node-problem-detector/README.md
- stable/node-problem-detector/templates/psp.yaml
* Updated psp to explicitly allow prometheus port range on host when hostNetwork is set
> [stable/node-problem-detector] Update psp to explicitly allow prometheus ports

- stable/locust/Chart.yaml
- stable/locust/README.md
- stable/locust/templates/master-deployment.yaml
- stable/locust/templates/master-serviceaccount.yaml
- stable/locust/templates/worker-deployment.yaml
- stable/locust/templates/worker-serviceaccount.yaml
- stable/locust/values.yaml
> [stable/locust] add serviceAccounts

- README.md
- stable/datadog-controller/.helmignore
- stable/datadog-controller/Chart.yaml
- stable/datadog-controller/README.md
- stable/datadog-controller/ci/ct-values.yaml
- stable/datadog-controller/templates/NOTES.txt
- stable/datadog-controller/templates/_helpers.tpl
- stable/datadog-controller/templates/clusterrole.yaml
- stable/datadog-controller/templates/clusterrolebinding.yaml
- stable/datadog-controller/templates/crd.yaml
- stable/datadog-controller/templates/deployment.yaml
- stable/datadog-controller/templates/secret.yaml
- stable/datadog-controller/templates/serviceaccount.yaml
- stable/datadog-controller/values.yaml
> [stable/datadog-controller] add chart

- stable/node-problem-detector/Chart.yaml
- stable/node-problem-detector/README.md
- stable/node-problem-detector/values.yaml
Update `node-problem-detector` chart to latest recently release version.
> [stable/node-problem-detector] Update to v0.8.5

- stable/locust/Chart.yaml
- stable/locust/README.md
- stable/locust/templates/master-deployment.yaml
- stable/locust/templates/worker-deployment.yaml
- stable/locust/values.yaml
Also custom docker image per worker/master.
Resolves https://github.com/deliveryhero/helm-charts/issues/77
> [stable/locust] update version, add options for command and args

- stable/cachet/Chart.yaml
- stable/cachet/README.md
- stable/cachet/templates/deployment.yaml
- stable/cachet/values.yaml
Signed-off-by: Thomas Nyambati <thomasnyambati@gmail.com>
> [stable/cachet] add to cachet podLabels

- stable/locust/Chart.yaml
- stable/locust/README.md
- stable/locust/templates/master-deployment.yaml
- stable/locust/templates/worker-deployment.yaml
- stable/locust/values.yaml
Added possibility to set update strategy. Should be merged after https://github.com/deliveryhero/helm-charts/pull/82, if it looks fine.
> [stable/locust] Add update strategy to values

- README.md
- stable/pg-repack-scheduler/.helmignore
- stable/pg-repack-scheduler/Chart.yaml
- stable/pg-repack-scheduler/README.md
- stable/pg-repack-scheduler/files/SQL/install_maint_schema.sql
- stable/pg-repack-scheduler/files/dockerfile
- stable/pg-repack-scheduler/files/entrypoint.sh
- stable/pg-repack-scheduler/files/run_pg_repack.sh
- stable/pg-repack-scheduler/templates/_helpers.tpl
- stable/pg-repack-scheduler/templates/cronjob.yaml
- stable/pg-repack-scheduler/templates/secret.yaml
- stable/pg-repack-scheduler/values.yaml
> [stable/pg-repack-scheduler] add chart

- stable/k8s-resources/Chart.yaml
- stable/k8s-resources/README.md
- stable/k8s-resources/ci/ct-values.yaml
- stable/k8s-resources/templates/cronjob.yaml
- stable/k8s-resources/values.yaml
> [stable/k8s-resources] add CronJob

- stable/labelsmanager-controller/.helmignore
- stable/labelsmanager-controller/Chart.yaml
- stable/labelsmanager-controller/README.md
- stable/labelsmanager-controller/templates/_helpers.tpl
- stable/labelsmanager-controller/templates/crd.yaml
- stable/labelsmanager-controller/templates/daemonset.yaml
- stable/labelsmanager-controller/templates/rbac.yaml
- stable/labelsmanager-controller/values.yaml
> [stable/labelsmanager-controller]add labels manager controller

- stable/node-problem-detector/Chart.yaml
- stable/node-problem-detector/README.md
- stable/node-problem-detector/templates/daemonset.yaml
> [stable/node-problem-detector] add labels to pod metadata

- stable/locust/Chart.yaml
- stable/locust/README.md
- stable/locust/values.yaml
Add a missing comment in locust README
> [stable/locust]Fix locust README comment

- README.md
> Update README.md: add Artifact Hub badge

- stable/backstage/Chart.lock
- stable/backstage/Chart.yaml
- stable/backstage/README.md
- stable/backstage/files/app-config.development.yaml.tpl
- stable/backstage/files/create-backend-dbs.sql
- stable/backstage/templates/_helpers.tpl
- stable/backstage/templates/backend-deployment.yaml
- stable/backstage/templates/backend-secret.yaml
- stable/backstage/templates/backstage-app-config.yaml
- stable/backstage/templates/backstage-auth-config.yaml
- stable/backstage/templates/frontend-deployment.yaml
- stable/backstage/templates/ingress.yaml
- stable/backstage/templates/lighthouse-config.yaml
- stable/backstage/templates/lighthouse-deployment.yaml
- stable/backstage/templates/postgresql-certs-secret.yaml
- stable/backstage/templates/postgresql-initdb-secret.yaml
- stable/backstage/templates/postgresql-password-secret.yaml
- stable/backstage/values.yaml
> [stable/backstage] Add backstage chart

- stable/backstage/Chart.lock
- stable/backstage/Chart.yaml
- stable/backstage/README.md
- stable/backstage/templates/databases.yaml
- stable/backstage/values.yaml
> [stable/backstage] Add pg database manifest to backstage

- stable/locust/Chart.yaml
- stable/locust/README.md
- stable/locust/templates/master-pdb.yaml
- stable/locust/values.yaml
> [stable/locust] add PodDisruptionBudget for master

- stable/rds-downscaler/Chart.yaml
- stable/rds-downscaler/README.md
- stable/rds-downscaler/config/run.py
- stable/rds-downscaler/templates/cronjob.yaml
- stable/rds-downscaler/values.yaml
Update rds-downscaler chart to stop a particular db instance
> [stable/rds-downscaler] Update rds-downscaler to stop specific instances

- stable/rds-downscaler/Chart.yaml
- stable/rds-downscaler/README.md
- stable/rds-downscaler/config/run.py
- stable/rds-downscaler/templates/cronjob.yaml
- stable/rds-downscaler/values.yaml
Update rds-downscaler script to shut down specified aurora clusters
> [stable/rds-downscaler] Update rds-downscaler script to shut down specified aurora clusters

- stable/hoppscotch/Chart.yaml
- stable/hoppscotch/README.md
- stable/hoppscotch/templates/ingress.yaml
- stable/hoppscotch/values.yaml
The hoppscotch charts ingress object was not working as intended.
> [stable/hoppscotch]: correct hoppscotch ingress object

- README.md
- stable/prometheus-locust-exporter/.helmignore
- stable/prometheus-locust-exporter/Chart.yaml
- stable/prometheus-locust-exporter/README.md
- stable/prometheus-locust-exporter/templates/NOTES.txt
- stable/prometheus-locust-exporter/templates/_helpers.tpl
- stable/prometheus-locust-exporter/templates/deployment.yaml
- stable/prometheus-locust-exporter/templates/service.yaml
- stable/prometheus-locust-exporter/values.yaml
> [stable/prometheus-locust-exporter] add chart

- stable/node-problem-detector/Chart.yaml
- stable/node-problem-detector/README.md
- stable/node-problem-detector/values.yaml
This PR bumps the node-problem-detector to v0.8.7.
Here are the logs:
```bash
kubectl logs node-problem-detector-b6jsj
I0223 21:26:29.085373       1 log_monitor.go:79] Finish parsing log monitor config file /config/kernel-monitor.json: {WatcherConfig:{Plugin:kmsg PluginConfig:map[] LogPath:/dev/kmsg Lookback:5m Delay:} BufferSize:10 Source:kernel-monitor DefaultConditions:[{Type:KernelDeadlock Status: Transition:0001-01-01 00:00:00 +0000 UTC Reason:KernelHasNoDeadlock Message:kernel has no deadlock} {Type:ReadonlyFilesystem Status: Transition:0001-01-01 00:00:00 +0000 UTC Reason:FilesystemIsNotReadOnly Message:Filesystem is not read-only}] Rules:[{Type:temporary Condition: Reason:OOMKilling Pattern:Killed process \d+ (.+) total-vm:\d+kB, anon-rss:\d+kB, file-rss:\d+kB.*} {Type:temporary …
```
> [stable/node-problem-detector] bump node-problem-detector to v0.8.7

- README.md
It seems many people run it from chart directory
> Update README.md: add note about running docs from repo root

- README.md
- stable/prometheus-cloudflare-exporter/.helmignore
- stable/prometheus-cloudflare-exporter/Chart.yaml
- stable/prometheus-cloudflare-exporter/README.md
- stable/prometheus-cloudflare-exporter/templates/_helpers.tpl
- stable/prometheus-cloudflare-exporter/templates/deployment.yaml
- stable/prometheus-cloudflare-exporter/templates/secret.yaml
- stable/prometheus-cloudflare-exporter/templates/service.yaml
- stable/prometheus-cloudflare-exporter/values.yaml
> [stable/prometheus-cloudflare-exporter] Add chart

- stable/prometheus-locust-exporter/Chart.yaml
- stable/prometheus-locust-exporter/README.md
- stable/prometheus-locust-exporter/values.yaml
> [stable/prometheus-locust-exporter] update version

- .github/workflows/markdown-lint.yml
- README.md
> Add instruction on how to run markdown-lint locally

- README.md
> Update README.md, fix typo

- stable/locust/Chart.yaml
- stable/locust/README.md
- stable/locust/templates/master-ingress.yaml
- stable/locust/values.yaml
Resolves https://github.com/deliveryhero/helm-charts/issues/128
> [stable/locust] make ingress path configurable

- stable/superset/Chart.yaml
- stable/superset/README.md
- stable/superset/ci/ct-values.yaml
- stable/superset/templates/database.yaml
- stable/superset/templates/deployment-worker.yaml
- stable/superset/values.yaml
> [stable/superset] add create db resource

- stable/superset/Chart.yaml
- stable/superset/README.md
- stable/superset/templates/configmap.yaml
- stable/superset/values.yaml
> [stable/superset] fix configmap variable mismatch

- stable/kubecost-reports-exporter/Chart.yaml
- stable/kubecost-reports-exporter/README.md
- stable/kubecost-reports-exporter/templates/aggregated-reports.yaml
> [stable/kubecost-reports-exporter] fix service account

- stable/kubecost-reports-exporter/Chart.yaml
- stable/kubecost-reports-exporter/README.md
- stable/kubecost-reports-exporter/templates/aggregated-reports.yaml
> fix service account bug

- stable/kubecost-reports-exporter/Chart.yaml
- stable/kubecost-reports-exporter/README.md
- stable/kubecost-reports-exporter/templates/aggregated-reports.yaml
- stable/kubecost-reports-exporter/templates/non-aggregated-reports.yaml
- stable/kubecost-reports-exporter/values.yaml
> [stable/kubecost-reports-exporter] add concurrency policy

- stable/superset/Chart.yaml
- stable/superset/README.md
- stable/superset/templates/configmap.yaml
- stable/superset/templates/deployment-superset.yaml
- stable/superset/templates/ingress.yaml
- stable/superset/templates/job-db-init.yaml
- stable/superset/templates/job-db-upgrade.yaml
- stable/superset/values.yaml
> [stable/superset] add oidc config

- stable/superset/Chart.yaml
- stable/superset/README.md
- stable/superset/templates/ingress.yaml
Signed-off-by: Thomas Nyambati <thomasnyambati@gmail.com>
> [stable/superset]fix labels mismatch

- stable/superset/Chart.yaml
- stable/superset/README.md
- stable/superset/ci/ct-values.yaml
- stable/superset/templates/configmap.yaml
- stable/superset/templates/deployment-celery-beat.yaml
- stable/superset/templates/deployment-superset.yaml
- stable/superset/templates/deployment-worker.yaml
- stable/superset/templates/job-create-user.yaml
- stable/superset/templates/job-db-init.yaml
- stable/superset/templates/job-db-upgrade.yaml
- stable/superset/templates/secrets.yaml
- stable/superset/values.yaml
> [stable/superset] reload on config change

- stable/superset/Chart.yaml
- stable/superset/README.md
- stable/superset/templates/_helpers.tpl
- stable/superset/templates/configmap.yaml
- stable/superset/templates/secrets.yaml
> [stable/superset] fix redis url

- stable/superset/Chart.yaml
- stable/superset/README.md
- stable/superset/templates/job-create-user.yaml
- stable/superset/templates/job-db-init.yaml
- stable/superset/templates/job-db-upgrade.yaml
Signed-off-by: Thomas Nyambati <thomasnyambati@gmail.com>
> [stable/superset]delete hooks on success and fail

- stable/superset/Chart.yaml
- stable/superset/README.md
- stable/superset/templates/configmap.yaml
- stable/superset/values.yaml
> [stable/superset] extend superset configmap

- stable/locust/Chart.yaml
- stable/locust/README.md
- stable/locust/templates/worker-deployment.yaml
- `--tag` argument is incorrect but it worked😅, update to `--tags`
- locust docs: https://docs.locust.io/en/1.0.3/writing-a-locustfile.html#tagging-tasks
> [stable/locust] update `--tag` to `--tags`

- .github/workflows/helm-docs.yml
- README.md
- ci/helm-docs.sh
- stable/backstage/Chart.yaml
- stable/backstage/README.md
- stable/prometheus-aws-costs-exporter/Chart.yaml
- stable/prometheus-aws-costs-exporter/README.md
- stable/weblate/Chart.yaml
- stable/weblate/README.md
- helm-docs: bump version to [v1.5.0](https://github.com/norwoodj/helm-docs/releases/tag/v1.5.0)
- update README.md
- fix AppVersion badge not found
- fix environment type
> [stable/backstage] [stable/prometheus-aws-costs-exporter] [stable/weblate] helm-docs: bump version to v1.5.0 & update README.md

- README.md
- stable/wiremock/.helmignore
- stable/wiremock/Chart.yaml
- stable/wiremock/README.md
- stable/wiremock/templates/_helpers.tpl
- stable/wiremock/templates/configmap-config.yaml
- stable/wiremock/templates/deployment.yaml
- stable/wiremock/templates/hpa.yaml
- stable/wiremock/templates/ingress.yaml
- stable/wiremock/templates/service.yaml
- stable/wiremock/values.yaml
This PR introduces a [WireMock](http://wiremock.org/) chart for testing purposes.
> [stable/wiremock] initial introduction

- stable/wiremock/Chart.yaml
- stable/wiremock/README.md
- stable/wiremock/templates/deployment.yaml
- stable/wiremock/values.yaml
* introduce pod annotations
* fix deployment annotations
> [stable/wiremock] deployment and pod annotations

- stable/service-account/Chart.yaml
- stable/service-account/README.md
- stable/service-account/templates/_helpers.tpl
> [stable/service-account] fix YAML error

- stable/locust/Chart.yaml
- stable/locust/README.md
- stable/locust/templates/_helpers.tpl
> [stable/locust] fix load_test label

- stable/locust/Chart.yaml
- stable/locust/README.md
- stable/locust/values.yaml
> [stable/locust] update to latest version

- stable/locust/Chart.yaml
- stable/locust/README.md
- stable/locust/templates/_helpers.tpl
> [stable/locust] fix labels again

- stable/locust/Chart.yaml
- stable/locust/README.md
- stable/locust/templates/_helpers.tpl
- stable/locust/values.yaml
> [stable/locust] fix labels

- stable/toxiproxy/Chart.yaml
- stable/toxiproxy/README.md
- stable/toxiproxy/templates/pdb.yaml
> [stable/toxiproxy] Update pdb.yaml

- stable/toxiproxy/Chart.yaml
- stable/toxiproxy/README.md
- stable/toxiproxy/templates/pdb.yaml
> [stable/toxiproxy] remove label copied from locust chart

- README.md
- stable/cluster-overprovisioner/Chart.yaml
- stable/cluster-overprovisioner/README.md
- stable/cluster-overprovisioner/templates/pdb.yaml
- stable/cluster-overprovisioner/values.yaml
This PR will close the issue #173 .
I added the PodDisruptionBudget in the Helm Chart for cluster-overprovisioner.
> [stable/cluster-overprovisioner] Add PodDisruptionBudget

- stable/kubecost-reports-exporter/Chart.yaml
- stable/kubecost-reports-exporter/README.md
- stable/kubecost-reports-exporter/templates/_helpers.tpl
- stable/kubecost-reports-exporter/templates/aggregated-reports.yaml
- stable/kubecost-reports-exporter/templates/non-aggregated-reports.yaml
- stable/kubecost-reports-exporter/templates/serviceaccount.yaml
- stable/kubecost-reports-exporter/values.yaml
> [stable/kubecost-reports-exporter] add serviceaccount

- stable/aws-service-events-exporter/Chart.yaml
- stable/aws-service-events-exporter/README.md
- stable/aws-service-events-exporter/templates/deployment.yaml
- stable/aws-service-events-exporter/templates/serviceaccount.yaml
- stable/aws-service-events-exporter/values.yaml
> [stable/aws-service-events-exporter] add aws service events service account

- stable/backstage/Chart.yaml
- stable/backstage/README.md
- stable/backstage/templates/backstage-auth-config.yaml
Set github token value as environment variable
> [stable/backstage] Add github token to backstage auth config

- stable/backstage/Chart.yaml
- stable/backstage/README.md
- stable/backstage/templates/ingress.yaml
> Add Backstage ingress

- stable/backstage/Chart.yaml
- stable/backstage/templates/backend-secret.yaml
Set github token for software catalog
> [stable/backstage] Set GitHub token

- stable/prometheus-sentry-exporter/Chart.yaml
- stable/prometheus-sentry-exporter/README.md
- stable/prometheus-sentry-exporter/templates/deployment.yaml
- stable/prometheus-sentry-exporter/values.yaml
> [stable/prometheus-sentry-exporter] add pod annotations

- stable/prometheus-aws-limits-exporter/Chart.yaml
- stable/prometheus-aws-limits-exporter/README.md
- stable/prometheus-aws-limits-exporter/templates/deployment.yaml
- stable/prometheus-aws-limits-exporter/templates/service.yaml
> [stable/prometheus-aws-limits-exporter] update liveness/readiness endpoints

- stable/backstage-mono/Chart.yaml
- stable/backstage-mono/README.md
- stable/backstage-mono/templates/_helpers.tpl
- stable/backstage-mono/templates/deployment.yaml
- stable/backstage-mono/values.yaml
Adds extra labels to backstage resources
> [stable/backstage-mono]Add common labels to backstage resources

- stable/mlflow/Chart.yaml
- stable/mlflow/README.md
- stable/mlflow/values.yaml
Use specific image tag instead of "latest"
> [stable/mlflow] fix image version

- stable/aws-service-events-exporter/Chart.yaml
- stable/aws-service-events-exporter/README.md
- stable/aws-service-events-exporter/values.yaml
> [stable/aws-service-events-exporter] Update aws service events exporter image

- ci/helm-docs.sh
- stable/cachet/Chart.yaml
So it prints a diff of the expected `README.md` file changes as this is confusing to many contributors.
In action here: https://github.com/deliveryhero/helm-charts/pull/243/checks?check_run_id=3544882227#step:4:10
> Improve helm-docs CI script

- stable/kubecost-reports-exporter/Chart.yaml
- stable/kubecost-reports-exporter/README.md
- stable/kubecost-reports-exporter/templates/aggregated-reports.yaml
- stable/kubecost-reports-exporter/templates/non-aggregated-reports.yaml
- stable/kubecost-reports-exporter/values.yaml
> support multiple clusters

- stable/listmonk/Chart.yaml
- stable/listmonk/README.md
- stable/listmonk/ci/ct-values.yaml
- stable/listmonk/values.yaml
> [stable/listmonk] Fix postgresql enable condition

- stable/aws-storage-class/Chart.yaml
- stable/aws-storage-class/README.md
- stable/aws-storage-class/templates/storageclass-gp2.yaml
- stable/aws-storage-class/templates/storageclass-io1-10.yaml
- stable/aws-storage-class/templates/storageclass-io1-20.yaml
- stable/aws-storage-class/values.yaml
> [stable/aws-storage-class] allow change of volume bind mode

- stable/cortex-gateway/Chart.yaml
- stable/cortex-gateway/README.md
- stable/cortex-gateway/templates/_helpers.tpl
- stable/cortex-gateway/templates/deployment.yaml
- stable/cortex-gateway/values.yaml
> [stable/cortex-gateway] Extra labels cortexgateway

- stable/listmonk/Chart.yaml
- stable/listmonk/README.md
- stable/listmonk/templates/init-db.yaml
- stable/listmonk/values.yaml
> [stable/listmonk] Fix listmonk init db job condition

- stable/listmonk/Chart.yaml
- stable/listmonk/README.md
- stable/listmonk/templates/configmap.yaml
> [stable/listmonk] Fix listmonk configmap labels

- stable/cortex-gateway/Chart.yaml
- stable/cortex-gateway/README.md
- stable/cortex-gateway/templates/deployment.yaml
- stable/cortex-gateway/values.yaml
Update cortex-gateway chart for 1.0.2
> [stable/cortex-gateway] Update chart for cortex-gateway 1.0.2

- stable/kube-bench/Chart.yaml
- stable/kube-bench/README.md
- stable/kube-bench/templates/cron.yaml
- stable/kube-bench/values.yaml
> configurable concurrencyPolicy for kube-bench CronJob

- stable/labelsmanager-controller/Chart.yaml
- stable/labelsmanager-controller/README.md
- stable/labelsmanager-controller/templates/crd.yaml
- stable/labelsmanager-controller/templates/daemonset.yaml
> labelsmanager set pod labels

- stable/cortex-gateway/Chart.yaml
- stable/cortex-gateway/README.md
- stable/cortex-gateway/templates/deployment.yaml
- stable/cortex-gateway/values.yaml
Specify deployment strategy for cortex gateway deployment
> [stable/cortex-gateway] Specify deployment strategy for cortex gateway deployment

- stable/mlflow/Chart.yaml
- stable/mlflow/README.md
- stable/mlflow/templates/deployment.yaml
> [stable/mlflow] fix mlflow helmchart

- stable/cortex-gateway/Chart.yaml
- stable/cortex-gateway/README.md
- stable/cortex-gateway/templates/deployment.yaml
- stable/cortex-gateway/values.yaml
> [stable/cortex-gateway] Add Alertmanager arg to cortex-gateway chart

- stable/kube-downscaler/Chart.yaml
- stable/kube-downscaler/README.md
- stable/kube-downscaler/templates/clusterrole.yaml
- stable/kube-downscaler/values.yaml
same rules as upstream project:
https://codeberg.org/hjacobs/kube-downscaler/src/branch/main/deploy/rbac.yaml
> [stable/kube-downscaler] sync cluster role with upstream

- stable/node-problem-detector/Chart.yaml
- stable/node-problem-detector/README.md
- stable/node-problem-detector/templates/prometheusrule.yaml
- stable/node-problem-detector/values.yaml
Adds PrometheusRule CR if metrics are enabled with default alerts
> [stable/node-problem-detector]: add prometheusrule support

- stable/k8s-resources/Chart.yaml
- stable/k8s-resources/README.md
- stable/k8s-resources/templates/priorityclass.yaml
- stable/k8s-resources/values.yaml
> add priority classes

- stable/kubecost-reports-exporter/Chart.yaml
- stable/kubecost-reports-exporter/README.md
- stable/kubecost-reports-exporter/docker/cost-exporter.py
> add request timeout

- stable/listmonk/Chart.yaml
- stable/listmonk/README.md
> [stable/listmonk] Update listmonk appVersion

- stable/listmonk/Chart.yaml
- stable/listmonk/README.md
- stable/listmonk/templates/upgrade-db.yaml
- stable/listmonk/values.yaml
> [stable/listmonk] Add upgrade database job

- stable/listmonk/Chart.yaml
- stable/listmonk/README.md
- stable/listmonk/templates/init-db.yaml
- stable/listmonk/templates/secret.yaml
- stable/listmonk/templates/upgrade-db.yaml
> [stable/listmonk] Add suffix to listmonk jobs

- stable/node-local-dns/Chart.yaml
- stable/node-local-dns/README.md
Adding missing app version to node-local-dns chart
> [stable/node-local-dns] Adding missing app version to node-local-dns chart

- stable/k8s-resources/Chart.yaml
- stable/k8s-resources/README.md
- stable/k8s-resources/templates/cronjob.yaml
> fix: updated default values syntax in cronjob template

- stable/mlflow/Chart.yaml
- stable/mlflow/README.md
- stable/mlflow/templates/service.yaml
- stable/mlflow/values.yaml
> [stable/mlflow] Add service annotations option

- stable/mlflow/Chart.yaml
- stable/mlflow/README.md
- stable/mlflow/templates/deployment.yaml
- stable/mlflow/templates/service.yaml
- stable/mlflow/values.yaml
> [stable/mlflow] optional https port

- stable/superset/Chart.yaml
- stable/superset/README.md
- stable/superset/files/okta.py
- stable/superset/templates/variables.py.tpl
* Fix: fixed TypeError in templated Python script
> [stable/superset] Fix: fixed TypeError in templated Python script

- stable/metabase/.helmignore
- stable/metabase/Chart.yaml
- stable/metabase/README.md
- stable/metabase/templates/NOTES.txt
- stable/metabase/templates/_helpers.tpl
- stable/metabase/templates/config.yaml
- stable/metabase/templates/configmap.yaml
- stable/metabase/templates/database-secret.yaml
- stable/metabase/templates/deployment.yaml
- stable/metabase/templates/ingress.yaml
- stable/metabase/templates/service.yaml
- stable/metabase/templates/ssl-secret.yaml
- stable/metabase/values.yaml
> [stable/metabase] Add metabase chart

- stable/metabase/Chart.yaml
- stable/metabase/README.md
- stable/metabase/templates/ingress.yaml
> update metabase ingress

- stable/datadog-controller/Chart.yaml
- stable/datadog-controller/README.md
- stable/datadog-controller/templates/crd.yaml
We have updated chartmuseum to latest version so I want to test that sync still works. So here I'll update this chart with its new source.
> [stable/datadog-controller] update source

- stable/kube-downscaler/Chart.yaml
- stable/kube-downscaler/README.md
- stable/kube-downscaler/templates/deployment.yaml
- stable/kube-downscaler/values.yaml
This makes the chart do what `helm create` does and makes future updates easier because we only need to update the version in one place.
> [stable/kube-downscaler] use appVersion from Chart.yaml

- stable/k8s-resources/Chart.yaml
- stable/k8s-resources/README.md
- stable/k8s-resources/templates/service.yaml
- stable/k8s-resources/values.yaml
> [k8s-resources] Add loadBalancerSourceRanges to service template

- stable/kube-downscaler/Chart.yaml
- stable/kube-downscaler/README.md
- stable/kube-downscaler/templates/clusterrole.yaml
- stable/kube-downscaler/values.yaml
Fix clusterrole for argocd rollouts
> Fix kube-downscaler clusterrole for argocd rollouts

- stable/locust/Chart.yaml
- stable/locust/README.md
- stable/locust/values.yaml
> [stable/locust]Bump Locust version to 2.12.1

- stable/node-problem-detector/Chart.yaml
- stable/node-problem-detector/README.md
- stable/node-problem-detector/templates/_helpers.tpl
Resolves #404
Fixes #404, as described the policy version in the original code does not exist.
> [stable/node-problem-detector] Fix PSP API Versions

- stable/aws-storage-class/Chart.yaml
- stable/aws-storage-class/README.md
- stable/aws-storage-class/templates/storageclass-gp3.yaml
- stable/aws-storage-class/values.yaml
Adding gp3 storage class in `aws-storage-class` chart
> [stable/aws-storage-class]: Add gp3 storage class

- stable/metabase/Chart.yaml
- stable/metabase/README.md
- stable/metabase/templates/deployment.yaml
- stable/metabase/templates/ingress.yaml
- stable/metabase/values.yaml
* Update Metabase's chart and also its app version
* Partially resolves: [OGSYS-5999](https://jira.deliveryhero.com/browse/OGSYS-5999)
> [stable/metabase]: Update Metabase's chart and also its app version

- stable/weblate/Chart.yaml
- stable/weblate/README.md
- stable/weblate/templates/ingress.yaml
- stable/weblate/values.yaml
> [stable/weblate] update ingress API

- stable/wiremock/Chart.yaml
- stable/wiremock/README.md
- stable/wiremock/templates/pdb.yaml
> [stable/wiremock] update PDB policy API

- SECURITY.md
Set up a security policy pointing to our responsible disclosure form
> Set up a security policy

- stable/aws-service-quotas-exporter/Chart.yaml
- stable/aws-service-quotas-exporter/README.md
- stable/aws-service-quotas-exporter/templates/_helpers.tpl
- stable/aws-service-quotas-exporter/values.yaml
> [aws-service-quotas-exporter] add extra labels

- stable/locust/Chart.yaml
- stable/locust/README.md
- stable/locust/values.yaml
Updates the locust container version to the most recent (2.15.1)
> [stable/locust] Update container version

- stable/node-problem-detector/Chart.yaml
- stable/node-problem-detector/README.md
- stable/node-problem-detector/values.yaml
Change repo in response to https://kubernetes.io/blog/2023/02/06/k8s-gcr-io-freeze-announcement/
> [stable/node-problem-detector] Use registry.k8s.io

- stable/node-local-dns/Chart.yaml
- stable/node-local-dns/README.md
- stable/node-local-dns/values.yaml
Change repo in response to https://kubernetes.io/blog/2023/02/06/k8s-gcr-io-freeze-announcement/
> [stable/node-local-dns] Use registry.k8s.io

- stable/dregsy/Chart.yaml
- stable/dregsy/README.md
- stable/dregsy/templates/cronjob.yaml
- stable/dregsy/values.yaml
- update cronjon api version
- add failed job history limit
> update dregsy to cron manifest

- stable/dregsy/Chart.yaml
- stable/dregsy/README.md
- stable/dregsy/templates/cronjob.yaml
> [stable/dregsy] Add affinity to dregsy on cronjob mode

- stable/dregsy/Chart.yaml
- stable/dregsy/README.md
- stable/dregsy/templates/cronjob.yaml
- stable/dregsy/values.yaml
> [stable/dregsy] Fix dregsy affinity indentation

- stable/superset/Chart.yaml
- stable/superset/README.md
- stable/superset/templates/deployment-celery-beat.yaml
- stable/superset/templates/deployment-worker.yaml
- stable/superset/values.yaml
> [stable/superset] update superset celery command

- stable/k8s-resources/Chart.yaml
- stable/k8s-resources/README.md
- stable/k8s-resources/templates/scaledObject.yaml
- stable/k8s-resources/values.yaml
> [stable/k8s-resources] add keda scaled object

- stable/k8s-resources/Chart.yaml
- stable/k8s-resources/README.md
- stable/k8s-resources/templates/scaledObject.yaml
- remove default value from idle replica count
> remove default from idle replica count

- stable/k8s-event-logger/Chart.yaml
- stable/k8s-event-logger/README.md
- stable/k8s-event-logger/values.yaml
Resolves https://github.com/max-rocket-internet/k8s-event-logger/issues/21
> [stable/k8s-event-logger] update chart, docker image

- stable/node-problem-detector/Chart.yaml
- stable/node-problem-detector/README.md
- stable/node-problem-detector/values.yaml
Upgrade component version to version 0.8.13
> [stable/node-problem-detector]: 

- stable/k8s-event-logger/Chart.yaml
- stable/k8s-event-logger/README.md
- stable/k8s-event-logger/values.yaml
> [stable/k8s-event-logger] update to version 2.1

- stable/cortex-gateway/Chart.yaml
- stable/cortex-gateway/README.md
- stable/cortex-gateway/templates/service.yaml
- stable/cortex-gateway/values.yaml
> [stable/cortex-gateway] Add loadbalancerSourceRanges into cortex-gateway service

- stable/k8s-resources/Chart.yaml
- stable/k8s-resources/README.md
- stable/k8s-resources/templates/cronjob.yaml
> [stable/k8s-resources]: k8s 1.25 update cronjob deprecated apiversion

- stable/k8s-resources/Chart.yaml
- stable/k8s-resources/README.md
- stable/k8s-resources/templates/cronjob.yaml
> [stable/k8s-resources]: cronjob upgrade api to batch/v1  >= 1.24

- stable/superset/Chart.yaml
- stable/superset/README.md
- stable/superset/templates/hpa-celery.yaml
- stable/superset/templates/hpa-superset.yaml
- stable/superset/templates/hpa-worker.yaml
- update hpa superset api version
> [stable/superset] update superset hpa api version

- stable/superset/Chart.yaml
- stable/superset/README.md
- stable/superset/templates/hpa-celery.yaml
- stable/superset/templates/hpa-superset.yaml
- stable/superset/templates/hpa-worker.yaml
> update superset hpa configuration

- stable/node-problem-detector/Chart.yaml
- stable/node-problem-detector/README.md
- stable/node-problem-detector/values.yaml
This PR is just to update the image tag for NPD to the latest available.
> [stable/node-problem-detector] update image tag

- stable/field-exporter/Chart.yaml
- stable/field-exporter/README.md
- stable/field-exporter/templates/manager-rbac.yaml
> [stable/field-exporter]: add watch permission for secret

- stable/kubecost-reports-exporter/Chart.yaml
- stable/kubecost-reports-exporter/README.md
- stable/kubecost-reports-exporter/templates/allocation-assets-reports.yaml
- stable/kubecost-reports-exporter/values.yaml
- add failedJobsHistoryLimit kubecost
> add failedJobsHistoryLimit kubecost

- stable/node-problem-detector/Chart.yaml
- stable/node-problem-detector/README.md
- stable/node-problem-detector/values.yaml
Update image to fix arm support
Fixes https://github.com/deliveryhero/helm-charts/issues/532
> [stable/node-problem-detector] Update image to fix arm support

- stable/field-exporter/Chart.yaml
- stable/field-exporter/README.md
- stable/field-exporter/values.yaml
Releases version 1.3.1 of the controller
https://github.com/deliveryhero/field-exporter/compare/v1.3.0...v1.3.1
> [stable/field-exporter] update field-exporter chart

- .github/workflows/check_pr.yaml
- README.md
- Adjust `PR Title Checker` to be a bit more chill
- Separate helm-docs instructions for pre-commit vs docker
> [stable/NONE] Disable `PR Title Checker` github action, update README

- stable/node-local-dns/Chart.yaml
- stable/node-local-dns/README.md
https://github.com/kubernetes/dns/releases/tag/1.23.1
> [stable/node-local-dns]: update to 1.23.1

- stable/listmonk/Chart.yaml
- stable/listmonk/README.md
- stable/listmonk/templates/hpa.yaml
Update HPA API Version (autoscaling/v2beta1 -> autoscaling/v2)
> [stable/listmonk]: Update HPA API Version (autoscaling/v2beta1 -> autoscaling/v2)

- stable/hoppscotch/Chart.yaml
- stable/hoppscotch/README.md
- stable/hoppscotch/values.yaml
Update hoppscotch chart to use correct image.
Fixes: https://github.com/deliveryhero/helm-charts/issues/599
> [stable/hoppscotch] Update hoppscotch chart to use correct image

- stable/node-local-dns/Chart.yaml
- stable/node-local-dns/README.md
- stable/node-local-dns/templates/configmap.yaml
- stable/node-local-dns/values.yaml
> [stable/node-local-dns]: Add option to enable logging

- .github/workflows/helm-publish.yaml
> Add PR scope to helm-publish workflow

- .github/workflows/helm-publish.yaml
> Fix: workflow indentation

- stable/node-problem-detector/Chart.yaml
- stable/node-problem-detector/README.md
- stable/node-problem-detector/templates/daemonset.yaml
Follow-up to: https://github.com/deliveryhero/helm-charts/pull/686
> [stable/node-problem-detector]: Skip volumeMount if volume disabled for NPD

- stable/node-local-dns/Chart.yaml
- stable/node-local-dns/README.md
- stable/node-local-dns/templates/daemonset.yaml
#fixes https://github.com/deliveryhero/helm-charts/issues/698
> [stable/node-local-dns] Fix pod annotations condition

- stable/node-local-dns/Chart.yaml
- stable/node-local-dns/README.md
Mostly security fixes by updating dependencies, go version and base image version.
https://github.com/kubernetes/dns/compare/1.23.1...1.26.4
> [stable/node-local-dns] Update to latest version
