- stable/kube-downscaler/Chart.yaml
- stable/kube-downscaler/README.md
- stable/kube-downscaler/templates/_helpers.tpl
- stable/kube-downscaler/templates/clusterrole.yaml
- stable/kube-downscaler/templates/clusterrolebinding.yaml
- stable/kube-downscaler/templates/cronjob.yaml
- stable/kube-downscaler/templates/deployment.yaml
- stable/kube-downscaler/templates/serviceaccount.yaml
- stable/kube-downscaler/values.yaml
This will periodically remove the annotations preventing downscaling. Adding because many of our developers add the annotation to run a load test over night or something similar and then never remove it, incurring extra AWS costs.
Also making labels and templating more modern for this chart.
> [stable/kube-downscaler] Add cronjob to remove annotations periodically

- stable/toxiproxy/Chart.yaml
- stable/toxiproxy/README.md
- stable/toxiproxy/templates/_helpers.tpl
- stable/toxiproxy/templates/deployment.yaml
- stable/toxiproxy/templates/service.yaml
- Fixed trying to use the same `name` for all the ports defined in `Values.service.proxies.ports`
- Fixed wrong mapping when trying to specify extra labels that should be applied to the resources. 
- Fixed wrong indentation when specifying resources.
> [stable/toxiproxy] Misc fixes

- stable/toxiproxy/Chart.yaml
- stable/toxiproxy/README.md
- stable/toxiproxy/templates/configmap-proxies.yaml
- stable/toxiproxy/templates/deployment.yaml
- stable/toxiproxy/values.yaml
> [stable/toxiproxy] allow passing configmap to chart to store toxics

- stable/kube-bench/Chart.yaml
- stable/kube-bench/README.md
- stable/kube-bench/values.yaml
This PR removes app version from the chart.yaml file as the chart is not tied to a specific version of kube-bench. The version of kube-bench to be used can be specified using the values.yaml file. It also sets the default value of kube-bench image tag to latest.
> [stable/kube-bench] Use latest image of kube-bench for security tests

- stable/node-problem-detector/Chart.yaml
- stable/node-problem-detector/README.md
- stable/node-problem-detector/templates/daemonset.yaml
- stable/node-problem-detector/templates/psp.yaml
- stable/node-problem-detector/values.yaml
* Fixed when `hostNetwork` is set the psp will not allow `hostNetwork` pods to start
* Added `hostPID` to expose the host pid namespace for node problem detector
* Updated the node problem detector image repository & version to latest release, v0.8.4
> [stable/node-problem-detector] Fix psp with hostNetwork and allow setting hostPID

- stable/locust/Chart.yaml
- stable/locust/README.md
- stable/locust/templates/NOTES.txt
Locust chart deployments with service type set to NodePort or LoadBalancer fails. This PR fixes it.
> [stable/locust] Fix NOTES

- stable/locust/Chart.yaml
- stable/locust/README.md
- stable/locust/templates/master-service.yaml
Service annotations are in values but not in service manifest.
> [stable/locust] Fix service annotations

- stable/locust/Chart.yaml
- stable/locust/README.md
- stable/locust/templates/worker-hpa.yaml
Hi, current hpa manifest is valid for `autoscaling/v2beta2` API, but `autoscaling/v1` is specified.
This PR fixes manifest to be compatible with `autoscaling/v1`
> [stable/locust] Fix hpa

- stable/cluster-overprovisioner/Chart.yaml
- stable/cluster-overprovisioner/README.md
- stable/cluster-overprovisioner/ci/ct-values.yaml
- stable/cluster-overprovisioner/templates/deployments.yaml
- stable/cluster-overprovisioner/values.yaml
When using this helm chart we required annotations to be added directly to the top level Deployment object, rather than just at POD level so have updated the chart to use the `annotations` variable for the top level object, and have added a `podAnnotation` variable so POD level annotations can still be supported. This will be a breaking change for people using the `annotations` for POD level annotations, and they will need update inputs to use the `podAnnotations` variable instead.
I am happy for any suggested changes, or variable names to be adjusted. Thanks!
> [stable/cluster-overprovisioner]: Adding separate annotations to Pods and putting annotations on Deployment level

- stable/node-problem-detector/Chart.yaml
- stable/node-problem-detector/README.md
- stable/node-problem-detector/templates/daemonset.yaml
- stable/node-problem-detector/values.yaml
Add support for imagePullSecrets for downloading docker images from repository requiring
authentication. May come handy given dockerhub usage quotas introduction.
> [stable/node-problem-detector] Add support for imagePullSecrets

- stable/node-problem-detector/Chart.yaml
- stable/node-problem-detector/README.md
- stable/node-problem-detector/templates/daemonset.yaml
My previous PR introducing imagePullSecrets was incorrect, as it did not account 
for proper rendering of list. This PR fixes the issue. Using values.yaml as:
```
imagePullSecrets:
- name: secret1
- name: secret2
```
it renders properly:
```
imagePullSecrets:
- name: secret1
- name: secret2
```
Sorry for the mess...
> [stable/node-problem-detector] Fix rendering of imagePullSecrets

- stable/locust/Chart.yaml
- stable/locust/README.md
- stable/locust/templates/master-deployment.yaml
- stable/locust/templates/worker-deployment.yaml
- stable/locust/values.yaml
Allow config maps to be mounted in locust helm chart
> [stable/locust]Allow config maps to be mounted in locust helm chart

- stable/toxiproxy/Chart.yaml
- stable/toxiproxy/README.md
- stable/toxiproxy/templates/_helpers.tpl
- stable/toxiproxy/templates/deployment-frontend.yaml
- stable/toxiproxy/templates/ingress-frontend.yaml
- stable/toxiproxy/templates/service-frontend.yaml
- stable/toxiproxy/values.yaml
Added an optional frontend to ToxiProxy that is deployed as a separate pod.
> [stable/toxiproxy] Adding toxiproxy frontend

- stable/rds-downscaler/Chart.yaml
- stable/rds-downscaler/README.md
- stable/rds-downscaler/templates/cronjob.yaml
- stable/rds-downscaler/values.yaml
This PR handles the empty values for environment variables correctly for rds-downscaler chart. Default values for tag_key and tag_values has been set to empty strings.
> [stable/rds-downscaler] Handle empty env values

- stable/locust/Chart.yaml
- stable/locust/README.md
- stable/locust/templates/master-deployment.yaml
- stable/locust/templates/worker-deployment.yaml
- stable/locust/values.yaml
- Also removing liveliness probe as I don't think it's ever useful to have the master restarted.
- Add separate env vars for master/worker
- Add doc for master/worker `args`
Resolves https://github.com/deliveryhero/helm-charts/issues/108
> [stable/locust] add options for headless

- stable/cluster-overprovisioner/Chart.yaml
- stable/cluster-overprovisioner/README.md
- stable/cluster-overprovisioner/templates/_helpers.tpl
- stable/cluster-overprovisioner/templates/deployments.yaml
- stable/cluster-overprovisioner/templates/serviceaccount.yaml
- stable/cluster-overprovisioner/values.yaml
Add ability to use a non-default service account for the cluster-overprovisioner
> [stable/cluster-overprovisioner] Add service account to cluster-overprovisioner chart

- stable/kube-downscaler/Chart.yaml
- stable/kube-downscaler/README.md
- stable/kube-downscaler/templates/clusterrole.yaml
- stable/kube-downscaler/values.yaml
Hi :wave:
This updates the image used by the Helm chart to allow usage of the downscaler with HPAs. The `ClusterRole` has been amended to allow the `kube-downscaler` to interact with the API. 
A few links pointed to the archived github.com repos that Henning Jacobs used to use, I've updated the links to point at the new location on codeberg.org and added a link to this repo to help users discover more of your useful charts.
> [stable/kube-downscaler] upgrade image and clusterrole to enable usage with horizontalpodautoscalers 

- stable/node-problem-detector/Chart.yaml
- stable/node-problem-detector/README.md
- stable/node-problem-detector/templates/_helpers.tpl
- stable/node-problem-detector/templates/daemonset.yaml
- stable/node-problem-detector/templates/servicemonitor.yaml
- stable/node-problem-detector/values.yaml
This PR attempt to make the chart more flexible using different log directory in host and in pod. This improvement allows to keep default configuration even if the log directory is not on `/var/log/`. This modification implies Breaking Changes as `hostpath.logdir` is replaced by `logDir.host` and `logDir.pod` (see https://github.com/deliveryhero/helm-charts/commit/48c42008adbf9cfb1f37bf9f7ece8a0adf170b3d)
Another improvement is to move the node-problem-detector cli args to _helpers, this change make the chart more readable (see https://github.com/deliveryhero/helm-charts/commit/081204842f8efbc987b8a74b0d8a09955136dd2e)
> [stable/node-problem-detector] mountvolume and cli args improvement

- stable/node-problem-detector/Chart.yaml
- stable/node-problem-detector/README.md
- stable/node-problem-detector/templates/_helpers.tpl
Change cli flag `--config.custom-plugin-monitors` by `--config.custom-plugin-monitor`
Fix args spaces
Both issues introduced by https://github.com/deliveryhero/helm-charts/pull/123, my apologized
> [stable/node-problem-detector] fix npd cli args

- stable/locust/Chart.yaml
- stable/locust/README.md
- stable/locust/templates/master-ingress.yaml
- stable/locust/values.yaml
- Locust static files(e.g.  `./static/css/application.css?v=1.4.3` ) Not Found when I use ingress
- `locustio/locust:1.4.3` is released 2 months ago [(docker hub)](https://hub.docker.com/r/locustio/locust/tags?page=1&ordering=last_updated)
> [stable/locust] fix locust static files notfound when use ingress & use locust ver1.4.3

- stable/kubecost-reports-exporter/Chart.yaml
- stable/kubecost-reports-exporter/README.md
- stable/kubecost-reports-exporter/templates/aggregated-reports.yaml
- stable/kubecost-reports-exporter/templates/non-aggregated-reports.yaml
- stable/kubecost-reports-exporter/values.yaml
> [stable/kubecost-reports-exporter] fix kubecost url mismatch

- stable/cluster-overprovisioner/Chart.yaml
- stable/cluster-overprovisioner/README.md
- stable/cluster-overprovisioner/templates/deployments.yaml
- stable/cluster-overprovisioner/values.yaml
Add support for [pod topology spread constraints](https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/), and close #141. Also fix a few typos.
> [stable/cluster-overprovisioner] Support pod topology spread constraints

- stable/locust/Chart.yaml
- stable/locust/README.md
- stable/locust/templates/configmap-config.yaml
- stable/locust/templates/worker-deployment.yaml
- stable/locust/values.yaml
- added locust with `--tags [TAG [TAG ...]]` options, so only tasks with any matching tags will be executed
- added locust with `--exclude-tags [TAG [TAG ...]]` options, so only tasks with no matching tags will be executed
- fix `docker-entrypoint.sh` doesn't work with list arguments(e.g. `--tags tag1 tag2`)
- locust docs: https://docs.locust.io/en/1.0.3/writing-a-locustfile.html#tagging-tasks
> [stable/locust] add options for tags & excludeTags

- stable/cluster-overprovisioner/Chart.yaml
- stable/cluster-overprovisioner/README.md
- stable/cluster-overprovisioner/templates/deployments.yaml
Fix the whitespace error introduce in #142.
> [stable/cluster-overprovisioner] Fix whitespace in topologySpreadConstraints

- stable/wiremock/Chart.yaml
- stable/wiremock/README.md
- stable/wiremock/templates/pdb.yaml
- stable/wiremock/values.yaml
This can stop k8s moving these pods for node down scaling.
> [stable/wiremock] add PodDisruptionBudget

- stable/locust/Chart.yaml
- stable/locust/README.md
- stable/locust/templates/_helpers.tpl
- stable/locust/templates/master-deployment.yaml
- stable/locust/templates/worker-deployment.yaml
Update master and worker deployment templates to define volumes for mounted `extraConfigMaps`.
Improved template definitions for master, worker and service definitions.
~~Added recommended k8s label definitions to solve failing conftest~~ will be checked separately
> [stable/locust] define extra configmap volumes

- stable/locust/Chart.yaml
- stable/locust/README.md
- stable/locust/templates/master-deployment.yaml
- stable/locust/templates/secret.yaml
- stable/locust/templates/worker-deployment.yaml
- stable/locust/values.yaml
- There is a value `environment_secret` that creates a secret and mounts its keys as environment variables. This was, however, not documented, so I added the details to `values.yaml` and the README.
- If `environment_secret` was not set, an empty secret with name `locust` would be created. I changed this, so the secret is only created if there is data to fill it with.
- While this is great, when using GitOps tools like Flux, the contents of `values.yaml` are uploaded to Git, so this is not a great way to pass secrets to the deployment for these users. To avoid this, I added the `environment_external_secret` value, so an existing secret can be used for environment variables. This way you can create the secret some other way, without keeping its contents in plain text on Git. The format I'm …
> [stable/locust] add environment variables from existing secret

- stable/node-problem-detector/Chart.yaml
- stable/node-problem-detector/README.md
- stable/node-problem-detector/values.yaml
Hello, this PR fixes #174, node-problem-detector version upgraded to [v0.8.8](https://github.com/kubernetes/node-problem-detector/releases/tag/v0.8.8)
> [stable/node-problem-detector] Upgrade node-problem-detector to v0.8.8

- .github/workflows/chart-testing.yml
- .github/workflows/helm-conftest.yaml
- ci/helm-conftest.sh
- stable/backstage/Chart.yaml
- stable/backstage/README.md
- stable/backstage/ci/ct-values.yaml
PRs https://github.com/deliveryhero/helm-charts/pull/195 and https://github.com/deliveryhero/helm-charts/pull/194 were merged with failed CI tests. I've changed repo settings to prevent merging when tests are failing, even for admins.
So now I need to fix the current master as the failed tests are affecting other PRs.
The errors are:
```
helm-conftest running for chart: stable/backstage...
Error: parse error in "backstage/templates/ingress.yaml": template: backstage/templates/ingress.yaml:1: function "urlParse" not defined
```
And:
```
Error: Error linting charts: Error processing charts
------------------------------------------------------------------------------------------------------------------------
✖︎ backstage => (version: "0.1.11", path: "stable/backstage") > Chart version not …
```
> [stable/backstage] Fix chart, also fix CI conftest

- stable/node-problem-detector/Chart.yaml
- stable/node-problem-detector/README.md
- stable/node-problem-detector/values.yaml
This pr bumps `node-problem-detector` version to [v0.8.9](https://github.com/kubernetes/node-problem-detector/releases/tag/v0.8.9).
> [stable/node-problem-detector] Upgrade node-problem-detector to v0.8.9

- stable/locust/Chart.yaml
- stable/locust/README.md
- stable/locust/templates/master-deployment.yaml
Fixing a bug where multiple arguments are passed to the b64enc function, which expects only one argument. Now I pipe the result of the concatenation into the b64enc instead.
> [stable/locust] - UI Basic Auth Bug - Closes #202

- stable/locust/Chart.yaml
- stable/locust/README.md
- stable/locust/templates/configmap-locust-locustfile.yaml
Replace hard coded locustfile `main.py` with `.Values.loadtest.locust_locustfile`
> [stable/locust] Fix hard coded locustfile name

- stable/wiremock/Chart.yaml
- stable/wiremock/README.md
- stable/wiremock/templates/deployment.yaml
- stable/wiremock/values.yaml
This PR provides configuration settings to adjust the default `initContainer`s image and tag to be able to work around issues recently introduced by the [docker rate limiting](https://docs.docker.com/docker-hub/download-rate-limit/).
> [stable/wiremock] expose init container image configuration

- stable/toxiproxy/Chart.yaml
- stable/toxiproxy/README.md
- stable/toxiproxy/templates/deployment.yaml
- stable/toxiproxy/values.yaml
This PR provides configuration settings to adjust the default `initContainer`s image and tag to be able to work around issues recently introduced by the [docker rate limiting](https://docs.docker.com/docker-hub/download-rate-limit/).
> [stable/toxiproxy] expose init container image configuration

- stable/locust/Chart.yaml
- stable/locust/README.md
- stable/locust/templates/master-deployment.yaml
- stable/locust/templates/worker-deployment.yaml
- stable/locust/values.yaml
https://github.com/deliveryhero/helm-charts/pull/172 added a functionality to allow existing secret to be used as environment variables. But only one value for each secret can be passed. If we have multiple key value pairs in a secret, we are able to pass only one key value pair in their with previous syntax
```
environment_external_secret:
secret_name: env_var_name
```
This PR changes this to allow of list of environment variable to be passed.
```
environment_external_secret:
secret_name: [AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY]
```
> [stable/locust] allow multiple value to passed using environment_external_secret

- stable/backstage/README.md
- stable/cachet/Chart.yaml
- stable/cachet/README.md
- stable/cachet/templates/ingress.yaml
- stable/cachet/values.yaml
Update Ingress Ressource to networking.k8s.io/v1 and added ingressClassName
- [x ] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)
- [x ] I have read the [contribution instructions](https://github.com/deliveryhero/helm-charts#contributing), bumped chart version and regenerated the docs
> stable/cachet Update Ingress Ressource to v1

- stable/locust/Chart.yaml
- stable/locust/README.md
- stable/locust/templates/_helpers.tpl
- stable/locust/templates/master-deployment.yaml
- stable/locust/templates/worker-deployment.yaml
- stable/locust/values.yaml
#197 added the functionality to load multiple keys from an existent k8s secret into an environment variable.  I found out that sometimes we need the entire file mounted because of some limitation from the running environment:
```
locust@testpod:~$ xargs --show-limits </dev/null
Your environment variables take up 2810 bytes
```
This PR add a functionality to mount k8s secrets in a given mount location:
```
mount_external_secret:
mountPath: /my-secret-location
files:
secret_file_1: [key1, key2]
secret_file_2: [key1]
```
> [stable/locust] Add the capability to mount external secret files at a specific location

- stable/aws-service-events-exporter/Chart.yaml
- stable/aws-service-events-exporter/README.md
- stable/aws-service-events-exporter/templates/deployment.yaml
> [stable/aws-service-events-exporter] Fix deployment labels indentation

- stable/cluster-overprovisioner/Chart.yaml
- stable/cluster-overprovisioner/README.md
- stable/cluster-overprovisioner/templates/deployments.yaml
- stable/cluster-overprovisioner/templates/pdb.yaml
- stable/cluster-overprovisioner/templates/serviceaccount.yaml
Addresses https://github.com/deliveryhero/helm-charts/issues/216
This change updates the cluster-overprovisioner Helm chart to honor the Helm release namespace. This is a common pattern implemented in most Helm charts and allows clients to install the chart into a namespace by passing the standard `--namespace` flag to Helm.
> [stable/cluster-overprovisioner] Issue-216: Honor Helm release namespace

- stable/locust/Chart.yaml
- stable/locust/README.md
- stable/locust/templates/master-deployment.yaml
- stable/locust/templates/worker-deployment.yaml
- stable/locust/values.yaml
This PR makes some changes to the handling of parameters and environment variables in the chart:
- Currently, the [master](https://github.com/deliveryhero/helm-charts/blob/master/stable/locust/templates/master-deployment.yaml) and [worker](https://github.com/deliveryhero/helm-charts/blob/master/stable/locust/templates/worker-deployment.yaml) deployments don't handle arguments as expected.
Setting `Values.master.args` or `Values.workers.args` in the [values.yaml](https://github.com/deliveryhero/helm-charts/blob/master/stable/locust/values.yaml#L63) replaces all the default args, even if `Values.master.args_include_default` is true, which is not the expected outcome according to the comment/README. Also, other values (`Values.loadtest.headless`, `Values.master.auth.enabled`, …
> [stable/locust] Move configs to env variables, fix argument inclusion conditions

- stable/locust/Chart.yaml
- stable/locust/README.md
- stable/locust/values.yaml
I'm not really a contributor to this repo, and have no idea if this will work. I'm very unsure about the versioning scheme for instance. But because I raised the issue, I guess I have to at least attempt to fix it :)
Bumping minor version, not just patch, because going from locust 1.x to 2.x is a potentially breaking change.
I'm also a little unsure if you prefer version. number 0.20.0 or 0.20. I'm skipping the .0 because I've seen it done like that in other places in the repo.
> [stable/locust] Bump Locust version to 2.1.0. Fixes #219

- stable/aws-s3-proxy/Chart.yaml
- stable/aws-s3-proxy/README.md
- stable/aws-s3-proxy/templates/serviceaccount.yaml
- stable/aws-s3-proxy/values.yaml
This PR adds support for service account annotations.
> [stable/aws-s3-proxy]: provide support for serviceAccount annotations

- stable/locust/Chart.yaml
- stable/locust/README.md
- stable/locust/templates/master-deployment.yaml
- stable/locust/templates/worker-deployment.yaml
I broke the indentation of the master and worker deployments' extra arguments with https://github.com/deliveryhero/helm-charts/pull/220
Sorry 🙏🏻
> [stable/locust] Fix deployment arguments indentation

- stable/node-problem-detector/Chart.yaml
- stable/node-problem-detector/README.md
- stable/node-problem-detector/templates/service.yaml
- stable/node-problem-detector/values.yaml
The reason of decoupling service monitor from service is that sometimes
you want just to export the service and in your prometheus configuration
(prometheus-operator) define the service monitor for this service.
So it's better to have a separate flag for exposing the service instead of 
coupling it with service monitor.
> [stable/node-problem-detector] Split metrics enable flag from service monitor

- stable/mlflow/Chart.yaml
- stable/mlflow/README.md
- stable/mlflow/templates/serviceaccount.yaml
- stable/mlflow/values.yaml
> [stable/mlflow] fix metadata.name of serviceaccount object

- stable/node-problem-detector/Chart.yaml
- stable/node-problem-detector/README.md
- stable/node-problem-detector/values.yaml
This pr bumps `node-problem-detector` version to [v0.8.10](https://github.com/kubernetes/node-problem-detector/releases/tag/v0.8.10).
> [stable/node-problem-detector] Upgrade node-problem-detector to v0.8.10

- stable/mlflow/Chart.yaml
- stable/mlflow/README.md
- stable/mlflow/templates/deployment.yaml
- stable/mlflow/templates/service.yaml
- stable/mlflow/values.yaml
mlflow: fix the container target port for service object
> mlflow: fix the container target port for service object

- stable/mlflow/Chart.yaml
- stable/mlflow/README.md
- stable/mlflow/templates/deployment.yaml
- stable/mlflow/templates/service.yaml
- stable/mlflow/values.yaml
mlflow: Adding a fix for using a different value for targetport
> mlflow: Adding a fix for using a different value for targetport

- stable/node-problem-detector/Chart.yaml
- stable/node-problem-detector/README.md
- stable/node-problem-detector/templates/daemonset.yaml
Signed-off-by: Sahil Raja <sahilraja242@gmail.com>
Addresses #240 
The changes add namespace field in the daemonset yaml. This is a common pattern implemented in most Helm charts and allows clients to install the chart into a namespace by passing the standard --namespace flag to Helm.
> [stable/node-problem-detector] Issue-240: Added namespace field in daemonset template yaml

- stable/node-problem-detector/Chart.yaml
- stable/node-problem-detector/README.md
- stable/node-problem-detector/templates/custom-config-configmap.yaml
- stable/node-problem-detector/templates/serviceaccount.yaml
This adds the namespace to the service account and config map used by the node-problem-detector helm chart.
> [stable/node-problem-detector] add namespace to service account and config map

- stable/locust/Chart.yaml
- stable/locust/README.md
- stable/locust/templates/master-deployment.yaml
Swap out the `cat` function for manual concatenation. The [`cat`](https://helm.sh/docs/chart_template_guide/function_list/#cat) function adds spaces between the fields, which creates invalid manifests.
> [stable/locust] Concatenate username:password without adding spaces

- .github/workflows/push-chart.yaml
Helm push plugin uses cm-push command instead of push command now
> Fix command to push helm charts

- stable/prometheus-aws-limits-exporter/Chart.yaml
- stable/prometheus-aws-limits-exporter/README.md
- stable/prometheus-aws-limits-exporter/templates/servicemonitor.yaml
- stable/prometheus-aws-limits-exporter/values.yaml
Add an optional ServiceMonitor to support scraping from [Prometheus Operator](https://github.com/prometheus-operator/prometheus-operator)
> [stable/prometheus-aws-limits-exporter ] Add serviceMonitor

- stable/toxiproxy/Chart.yaml
- stable/toxiproxy/README.md
- stable/toxiproxy/templates/deployment.yaml
- stable/toxiproxy/values.yaml
Added a new field so that we can specify pod annotations to be used when installing the Toxiproxy chart. Changes are basically the same as what's already existing in the Wiremock charts.
> [stable/toxiproxy] Added pod annotations field to deployment template

- stable/prometheus-aws-limits-exporter/Chart.yaml
- stable/prometheus-aws-limits-exporter/README.md
- stable/prometheus-aws-limits-exporter/templates/deployment.yaml
In our deployment of the aws-limits-exporter, we experienced readiness/liveness probe timeouts and AWS rate limit exceedence. The reason for this is that all metrics are retrieved every time a probe is performed.
Since aws-limits-exporter version 0.5.0, there is a dedicated health endpoint.
This PR updates the appVersion to use the new aws-limits-exporter containing the health endpoint and updating the helm chart to use this health endpoint as readiness and liveness probe.
As the helm chart change requires appVersion at least to be 0.5.0, we increased the minor version of the Chart.
> [stable/prometheus-aws-limits-exporter] Update appVersion and use health endpoint

- stable/k8s-resources/Chart.yaml
- stable/k8s-resources/README.md
- stable/k8s-resources/ci/ct-values.yaml
- stable/k8s-resources/templates/secret.yaml
- stable/k8s-resources/values.yaml
I have some secrets that I template based on several other values.
I load those other values using helm-secrets. But, I need to combine them into a db connection string.
Using `tpl .tplB64Keys $` allows me to define the secret as a templatable value.
I opted to create a separate `tplB64Keys` so that this won't inadvertently affect anyone using `b64Keys`.
So, this should be backwards compatible.
> [stable/k8s-resources] Support tpl secret values via .Values.Secrets[].tplB64Keys

- stable/cluster-overprovisioner/Chart.yaml
- stable/cluster-overprovisioner/README.md
Update to cluster overprovisioner readme which contains a minor grammatical error.
> [stable/cluster-overprovisioner] fix typo in readme

- ci/helm-conftest.sh
- ci/helm-docs.sh
- stable/cluster-overprovisioner/Chart.yaml
- stable/cluster-overprovisioner/README.md
- stable/cluster-overprovisioner/templates/pdb.yaml
* PDB's are deprecated in policy/v1beta1 from 1.25
* fix helm-conftest.sh to be compliant with shellcheck and make
executable
* fix helm-docs.sh to be compliant with shellcheck
> [stable/cluster-overprovisioner] resolve pdb deprecation warning

- stable/locust/Chart.yaml
- stable/locust/README.md
- stable/locust/templates/master-deployment.yaml
The current implementation of health check with Basic Auth is incorrect due to an error in the code below:
```
{{- if .Values.master.auth.enabled }}
httpHeaders:
- name: Authorization
value: Basic {{ cat .Values.master.auth.username ":" .Values.master.auth.password | b64enc }}
```
to be more precise, `cat .Values.master.auth.username ":" .Values.master.auth.password` generates a string `username : password` (see spaces) according to the [Helm documentation](https://helm.sh/docs/chart_template_guide/function_list/#cat).
This results in a pod being unable to start since the base64 encoded Authorization header is not what locust is expecting (it should be a string **without** spaces):
```
Events:
Type     Reason     Age                   From               Message
----     ------     ---- …
```
> [stable/locust] Fix httpHeaders Authorization header value

- stable/locust/Chart.yaml
- stable/locust/README.md
- stable/locust/templates/master-deployment.yaml
- stable/locust/templates/worker-deployment.yaml
- stable/locust/values.yaml
Allow the locust master and worker pod restart policy to be tunable. Basically when I have `autoquit` option set, with `restartPolicy` set to `Always`, it will attempt to restart the pod even though I want it to terminate. This will allow me to tune it to `OnFailure`.
> [stable/locust] make restart policy tunable

- stable/cluster-overprovisioner/Chart.yaml
- stable/cluster-overprovisioner/README.md
- stable/cluster-overprovisioner/templates/deployments.yaml
- stable/cluster-overprovisioner/values.yaml
This commit allow to configure command and args for container.
> [stable/cluster-overprovisioner] allow configure command and args

- stable/cluster-overprovisioner/Chart.yaml
- stable/cluster-overprovisioner/README.md
Signed-off-by: Ihor Urazov <iurazov@healthjoy.com>
Update pause image to latest version. See https://github.com/kubernetes/kubernetes/blob/master/build/pause/CHANGELOG.md
NOTE: I updated README.md in-place instead of doing it though helm-docs. Seems helm-docs template changed and current README doesn't match template.
> [stable/cluster-overprovisioner] Update pause image to 3.6

- stable/net-exporter/Chart.yaml
- stable/net-exporter/README.md
- stable/net-exporter/templates/_helpers.tpl
- stable/net-exporter/templates/daemonset.yaml
- stable/net-exporter/templates/np.yaml
- stable/net-exporter/templates/psp.yaml
- stable/net-exporter/templates/rbac.yaml
- stable/net-exporter/templates/service-account.yaml
- stable/net-exporter/templates/service.yaml
- stable/net-exporter/values.yaml
* Moved [net-exporter](https://github.com/giantswarm/net-exporter/tree/v1.10.3)`v1.10.3` to deliveryhero/helm-charts
* License is Apache v2, see: https://github.com/giantswarm/net-exporter/blob/v1.10.3/LICENSE
> stable/net-exporter: Added a new chart net-exporter (from: giantswarm/net-exporter)

- stable/net-exporter/Chart.yaml
- stable/net-exporter/README.md
- stable/net-exporter/templates/_helpers.tpl
- stable/net-exporter/templates/daemonset.yaml
- stable/net-exporter/templates/rbac.yaml
- stable/net-exporter/templates/service-account.yaml
- stable/net-exporter/templates/service.yaml
- stable/net-exporter/values.yaml
* Minor change: flexible resource name, labels and selector to fit our use case
Example:
```yaml
- name: {{ $cluster.region }}-{{ $cluster.env }}-net-exporter
chart: deliveryhero/net-exporter
kubeContext: {{ $cluster.cluster }}
labels:
app: net-exporter
cluster: {{ $cluster.cluster }}
type: infra
values:
- name: {{ $cluster.region }}-{{ $cluster.env }}-net-exporter
- timeout: 5s
- selector:
app: net-exporter
rps_region: {{ $cluster.region }}
env: {{ $cluster.env }}
- additionalLabels:
team: infra
grafana: aVhTzk5Wz
dh_region: {{ $cluster.region }}
dh_env: {{ $cluster.env }}
dh_app: net-exporter
dh_tribe: RPS
dh_squad: infra
```
> [stable/net-exporter] Flexible resource name, labels and selector to fit our use case

- stable/locust/Chart.yaml
- stable/locust/README.md
- stable/locust/templates/master-deployment.yaml
- stable/locust/templates/worker-deployment.yaml
As per https://github.com/locustio/locust/pull/1976 the --tags/--exclude-tags are now passed through the master locust node.  The master will then pass them through to the workers.  I moved these arguments from the worker deployment to the master deployment.
> [stable/locust] Pass --tags/--exclude-tags through the locust master

- stable/locust/Chart.yaml
- stable/locust/README.md
- stable/locust/templates/configmap-locust-lib.yaml
- stable/locust/templates/configmap-locust-locustfile.yaml
- stable/locust/templates/master-deployment.yaml
- stable/locust/templates/worker-deployment.yaml
- stable/locust/values.yaml
Allows to specify the path of the lib and the locustfile. 
I also made the use of the configmap optional if not needed.
> [stable/locust] be able to choose the path of Locustfile and library.

- stable/locust/Chart.yaml
- stable/locust/README.md
- stable/locust/templates/worker-deployment.yaml
In current locust chart, the worker `spec.replicas` is set even when `worker.hpa.enabled` is `true`, and it causes problem in GitOps tool [Argo CD](https://argo-cd.readthedocs.io/en/stable/).
By design, Argo CD constantly compares resource in Kubernetes against their definition in git. In this case, Argo CD will try to set `spec.replicas` to `1` to match resource definition in git, however, `HorizontalPodAutoscaling` will try to set `spec.replicas` to properly value according to current worker loading. This discrepancy makes worker unstable.
To fix the issue, locust chart shall not set `spec.replicas` when `worker.hpa.enabled` is `true`.
> [stable/locust] Don't set worker replicas when hpa is enabled

- stable/node-problem-detector/Chart.yaml
- stable/node-problem-detector/README.md
- stable/node-problem-detector/templates/service.yaml
- stable/node-problem-detector/values.yaml
Allows setting of service object annotations to allow promtheus scraping to work in custom k8s cluster. 
e.g 
```
apiVersion: v1
kind: Service
metadata:
annotations:
prometheus.io/port: "3300"
prometheus.io/scrape: "true"
...
```
> [stable/node-problem-detector] feat: allow service annotations

- stable/cluster-overprovisioner/Chart.yaml
- stable/cluster-overprovisioner/README.md
- stable/cluster-overprovisioner/templates/deployments.yaml
- stable/cluster-overprovisioner/values.yaml
podSecurityContext was already supported, this change adds support for container
security context for things like `allowPrivilegeEscalation=false`,
`readOnlyRootFilesystem=true`, `capabilities = DROP ALL`, etc
> [stable/cluster-overprovisioner] Add support for containerSecurityContext

- stable/node-problem-detector/Chart.yaml
- stable/node-problem-detector/README.md
- stable/node-problem-detector/templates/prometheusrule.yaml
- stable/node-problem-detector/values.yaml
Adds additional labels to prometheusRules.
> [stable/node-problem-detector] add: additionalLabels for prometheusRules

- stable/listmonk/Chart.yaml
- stable/listmonk/README.md
- stable/listmonk/templates/init-db.yaml
- stable/listmonk/templates/upgrade-db.yaml
Enable init-db and upgrade-db hooks to be triggered by helm upgrade and helm install
> [stable/listmonk] Enable init-db and upgrade-db hooks by helm upgrade

- stable/prometheus-aws-limits-exporter/Chart.yaml
- stable/prometheus-aws-limits-exporter/README.md
- stable/prometheus-aws-limits-exporter/ci/ct-values.yaml
- stable/prometheus-aws-limits-exporter/templates/deployment.yaml
- stable/prometheus-aws-limits-exporter/values.yaml
- Add dynamic readiness and liveness probe
- Remove development mode
- Ignore deployment ci checks as it needs to collect aws trusted advisor metrics to get ready
> [stable/prometheus-aws-limits-exporter] Update aws limits exporter chart

- stable/prometheus-aws-health-exporter/Chart.yaml
- stable/prometheus-aws-health-exporter/README.md
- stable/prometheus-aws-health-exporter/templates/_helpers.tpl
- stable/prometheus-aws-health-exporter/templates/deployment.yaml
- stable/prometheus-aws-health-exporter/templates/serviceaccount.yaml
- stable/prometheus-aws-health-exporter/values.yaml
- Add serviceaccount to being able to attach it to Iam role
- Add podAnnotations to being able to add prometheus annotations to scrape automatically
> [stable/prometheus-aws-health-exporter] Add service account and pod annotations to aws health exporter chart

- stable/locust/Chart.yaml
- stable/locust/README.md
- stable/locust/templates/configmap-config.yaml
- stable/locust/values.yaml
This pull request Bump locust to `2.8.6` version.
> [stable/locust] Bump locust to version 2.8.6

- stable/node-problem-detector/Chart.yaml
- stable/node-problem-detector/README.md
- stable/node-problem-detector/templates/_helpers.tpl
The PSP apiVersion is now deprecated (since k8 version 1.21) - This pr is to address this for newer clusters. Tested using `helm template . --set rbac.pspEnabled=true | grep PodSecurityPolicy -B 1`
> [stable/node-problem-detector] - policy/v1beta1 is deprecated in 1.21

- stable/cloudhealth-collector/Chart.yaml
- stable/cloudhealth-collector/README.md
- stable/cloudhealth-collector/templates/clusterrole.yaml
- stable/cloudhealth-collector/templates/clusterrolebinding.yaml
- stable/cloudhealth-collector/templates/deployment.yaml
- stable/cloudhealth-collector/templates/secret.yaml
- stable/cloudhealth-collector/values.yaml
Adds values to use an existing secret for api_token.
> [stable/cloudhealth-collector] add existing secret values

- stable/k8s-resources/Chart.yaml
- stable/k8s-resources/README.md
- stable/k8s-resources/templates/secret.yaml
- stable/k8s-resources/values.yaml
I updated the heml template stable/k8s-resources/templates/secret.yaml to allow for a Secret type other than just Opaque.
> [stable/k8s-resources] allow secret type other than Opaque

- stable/k8s-event-logger/Chart.yaml
- stable/k8s-event-logger/README.md
- stable/k8s-event-logger/templates/clusterrole.yaml
- stable/k8s-event-logger/values.yaml
This PR updates the image tag of k8s-event-logger to 1.6. This version was released today 10th of June 2022 to address the vulnerabilities in the container.
> [stable/k8s-event-logger] Update image tag to 1.6 for k8s-event-logger

- stable/superset/Chart.yaml
- stable/superset/README.md
- stable/superset/files/superset_config.py
- stable/superset/templates/_helpers.tpl
- stable/superset/templates/configmap.yaml
- stable/superset/templates/variables.py.tpl
- stable/superset/values.yaml
* Improved readability by moving Python code away from configmap's yaml file in superset
* Python variables are set in a separate template file `variables.py.tpl`
```txt
superset_config.py: |-
+     import os
+     
+     cache_default_timeout = 300
+     cache_key_prefix = "superset_"
+     cache_redis_host = "REDACTED"
+     cache_redis_port = 6379
+     cache_redis_db = "0"
+     cache_redis_url = f"redis://{cache_redis_host}:{cache_redis_port}/{cache_redis_db}"
+     
+     sqlalchemy_database_engine = "postgresql+psycopg2"
+     sqlalchemy_database_username = os.getenv("DB_USERNAME", "")
+     sqlalchemy_database_password = os.getenv("DB_PASSWORD", "")
+     sqlalchemy_database_address = "REDACTED"
+     sqlalchemy_database_uri = …
```
> Chore: move Python code away from configmap's yaml file in superset

- stable/locust/Chart.yaml
- stable/locust/README.md
- stable/locust/templates/master-deployment.yaml
- stable/locust/test.yaml
- stable/locust/values.yaml
Adds the ability to assign master to a different node, backwards compatible with global assignments
> [stable/locust] Master nodeSelector, affinity, and tolerations

- stable/superset/Chart.yaml
- stable/superset/README.md
- stable/superset/files/okta.py
- stable/superset/templates/configmap.yaml
- stable/superset/templates/variables.py.tpl
- stable/superset/values.yaml
* deliveryhero/superset chart supports Oauth2 with Okta
> [stable/superset] Chore: Superset chart supports Oauth2 with Okta now

- stable/superset/Chart.yaml
- stable/superset/README.md
- stable/superset/files/okta.py
- stable/superset/templates/variables.py.tpl
- stable/superset/values.yaml
* Configureable https reverse proxy
* Flexible assignment of roles after authn
> [stable/superset] Fix: configureable https reverse proxy + flexible assignment of roles after authn

- stable/kube-bench/Chart.yaml
- stable/kube-bench/README.md
- stable/kube-bench/templates/cron.yaml
- stable/kube-bench/templates/serviceaccount.yaml
- stable/kube-bench/values.yaml
This update allows the creation of a service account.
> [stable/kube-bench] Allows creation of service account

- stable/kube-downscaler/Chart.yaml
- stable/kube-downscaler/README.md
- stable/kube-downscaler/templates/deployment.yaml
- stable/kube-downscaler/values.yaml
Previously `Values.securityContext` was not used in templates, this PR adds it and keeps it empty by default.
> [stable/kube-downscaler] add missing `securityContext` into templates

- stable/node-problem-detector/Chart.yaml
- stable/node-problem-detector/README.md
- stable/node-problem-detector/values.yaml
A new version of node-problem-detector has been released after a very long delay: https://github.com/kubernetes/node-problem-detector/releases/tag/v0.8.11. This PR updates the version to the latest, 0.8.11. I ran checks locally and they all passed.
> [stable/node-problem-detector] Update Version to v0.8.11

- stable/kube-downscaler/Chart.yaml
- stable/kube-downscaler/README.md
- stable/kube-downscaler/values.yaml
The appVersion in kube-downscaler was updated in #293 but the `image.tag` value still deploys the `21.2.0` version. This updates `image.tag` to match `appVersion`.
It might be preferable to use the `default` hack from `helm create` so we only need to set the `appVersion`. I can prepare such a PR if that should be preferred.
There is also a newer version 22.7.1 on codeberg, in the spirit of atmic changes, this only fixes releasing the current `appVersion` but i'll prepare a PR to bump downscaler as well once this is fixed.
> [stable/kube-downscaler]: match image.tag with appVersion

- stable/cluster-overprovisioner/Chart.yaml
- stable/cluster-overprovisioner/README.md
- stable/cluster-overprovisioner/templates/deployments.yaml
- stable/cluster-overprovisioner/values.yaml
This change allows using a custom scheduler for overprovision deployment pods. The schedulerName is unset by default which means the default-scheduler will be used.
> [stable/cluster-overprovisioner] Add support for schedulerName

- stable/kube-downscaler/Chart.yaml
- stable/kube-downscaler/README.md
As promised, here is the update to the latest version of kube-downscaler. I did some cursory testing on a kind environment and it scaled down my workloads as expected.
> stable/kube-downscaler: update from 22.2.0 to 22.7.1

- stable/kube-downscaler/Chart.yaml
- stable/kube-downscaler/README.md
- stable/kube-downscaler/templates/deployment.yaml
Currently `securityContext` has been placed under `Deployment.spec.template.spec`. But the `securityContext.readOnlyRootFilesystem` is field of container [securityContext
](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#securitycontext-v1-core)
Enabling these values:
```
securityContext: 
readOnlyRootFilesystem: true
runAsNonRoot: true
runAsUser: 1000
```
and deploying the chart throws an error:
```
"Error: unable to build kubernetes objects from release manifest: error validating \"\": error validating data: ValidationError(Deployment.spec.template.spec.securityContext): unknown field \"readOnlyRootFilesystem\" in io.k8s.api.core.v1.PodSecurityContext\n"
```
Looking at the [deployment manifest](https://codeberg.org/hjacobs/kube-downscaler/src/branch/main/deploy/deplo …
> [stable/kube-downscaler] Move securityContext to container level

- stable/locust/Chart.yaml
- stable/locust/README.md
- stable/locust/values.yaml
Updates Locust to 2.11.0
I was unable to run the GH actions in my fork, but I'm guessing they will run when I make this PR...
> [stable/locust] Bump Locust version to 2.11.0

- stable/cloudhealth-collector/Chart.yaml
- stable/cloudhealth-collector/README.md
- stable/cloudhealth-collector/templates/deployment.yaml
- stable/cloudhealth-collector/values.yaml
I need to run the cloudhealth-collector with annotations on the Deployment.
Currently only pod annotations are supported.
This change adds deployment annotations to the helm chart via
`.Values.deploymentAnnotations`.
> [stable/cloudhealth-collector] add deploymentAnnotations

- stable/kube-downscaler/Chart.yaml
- stable/kube-downscaler/README.md
- stable/kube-downscaler/templates/deployment.yaml
PR adds support for pod custom labels.
One of the use cases is running downscaler in EKS on fargate where a pod label selector is used to determine a workload to be scheduled on fargate.
- [+] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)
- [+] I have read the [contribution instructions](https://github.com/deliveryhero/helm-charts#contributing), bumped chart version and regenerated the docs
- [+] Github actions are passing
> [stable/kube-downscaler] Add support for pod custom labels

- stable/node-problem-detector/Chart.yaml
- stable/node-problem-detector/README.md
- stable/node-problem-detector/templates/daemonset.yaml
- stable/node-problem-detector/values.yaml
And set `system-node-critical` as a default priorityClass
In kubernetes v1.16 `scheduler.alpha.kubernetes.io/critical-pod` annotation was deprecated and `priorityClassName` is supposed to be used instead.
Fixes https://github.com/deliveryhero/helm-charts/issues/373
> [stable/node-problem-detector] Remove deprecated critical-pod annotation

- stable/node-problem-detector/Chart.yaml
- stable/node-problem-detector/README.md
- stable/node-problem-detector/values.yaml
Updating node-problem-detector to `v0.8.12`
> stable/node-problem-detector: Updating to v0.8.12

- stable/k8s-resources/Chart.yaml
- stable/k8s-resources/README.md
- stable/k8s-resources/ci/ct-values.yaml
- stable/k8s-resources/templates/ingress.yaml
- stable/k8s-resources/templates/namespace.yaml
- stable/k8s-resources/values.yaml
Fixes #377.
Add `defaultBackend` and `ingressClassName` values.
Switch from `hosts` values to `rules`. Rule can be defined without host and
also it better matches Ingress spec.
Also fix `secretName` indentation, it should be nested in `.spec.tls`.
Add ability to create Namespaces.
> [stable/k8s-resources] Ingress API version networking.k8s.io/v1 support, add Namespaces

- stable/metabase/Chart.yaml
- stable/metabase/README.md
- stable/metabase/templates/deployment.yaml
- stable/metabase/values.yaml
Add extraEnv to metabase chart to set environment variables in metabase container.
> [stable/metabase] Add extraEnv to metabase chart to set environment variables

- stable/node-local-dns/Chart.yaml
- stable/node-local-dns/README.md
- stable/node-local-dns/templates/daemonset.yaml
- stable/node-local-dns/values.yaml
This PR updates the node-local-dns chart to make the resource requests and limits configurable. The resource requests default to `25m` and `5Mi`, which is unchanged from the previous hard-coded values.
Limits is set to an empty object so by default the limits will not be set. Users can choose to set just the cpu, memory, or both.
> [stable/node-local-dns] Add support for configurable resource requests and limts

- stable/kube-downscaler/Chart.yaml
- stable/kube-downscaler/README.md
- stable/kube-downscaler/templates/deployment.yaml
- stable/kube-downscaler/values.yaml
PR to add support for `priorityClassName`. 
It's important that the `kube-downscaler` has the right priority, especially when it's running in an environment with the `cluster-autoscaler` enabled because, in the event of a cluster downscale (i.e the cluster-autoscaler reduces the number of running instances), the `kube-downscaler` must be placed in any node **with the first priority**.
- [+] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)
- [+] I have read the [contribution instructions](https://github.com/deliveryhero/helm-charts#contributing), bumped chart version and regenerated the docs
- [+] Github actions are passing
> [stable/kube-downscaler] Add support for priorityClassName

- stable/cluster-overprovisioner/Chart.yaml
- stable/cluster-overprovisioner/README.md
- stable/cluster-overprovisioner/templates/deployments.yaml
- stable/cluster-overprovisioner/values.yaml
It's nice to have the option to arbitrary environment variables to containers. This PR adds a list variable to the cluster-overprovisioner chart, which is templated into the deployment.yaml file.
> [stable/cluster-overprovisioner] Add arbitrary environment variable functionality

- stable/cloudhealth-collector/Chart.yaml
- stable/cloudhealth-collector/README.md
- stable/cloudhealth-collector/templates/deployment.yaml
- stable/cloudhealth-collector/values.yaml
It's nice to have the option to arbitrary environment variables to containers. This PR adds a `list` variable to the cloudhealth-collector chart, which are templated into the deployment.yaml file.
> [stable/cloudhealth-collector] Add arbitrary environment variable functionality

- stable/node-local-dns/Chart.yaml
- stable/node-local-dns/README.md
- stable/node-local-dns/templates/daemonset.yaml
Current the chart [stable/node-local-dns]  has podAnnotations at values.yaml but these values are not being used on the daemonset, this PR will fix that.
> [stable/node-local-dns] Add podAnnotations to the daemonset

- stable/kube-downscaler/Chart.yaml
- stable/kube-downscaler/README.md
- stable/kube-downscaler/templates/clusterrole.yaml
Add missing argo rollouts clusterrole rules
> [stable/kube-downscaler] Add missing argo rollouts clusterrole rules

- stable/node-problem-detector/Chart.yaml
- stable/node-problem-detector/README.md
- stable/node-problem-detector/templates/service.yaml
- stable/node-problem-detector/values.yaml
In chart `node-problem-detector` exposing metrics in Prometheus format can be enabled with `metrics.enabled=true`. It creates a K8s Service that exposes metrics on the below endpoint
```sh
node-problem-detector:20257/metrics
```
but does not attach required annotations to the Service. To install and enable scrapping variable `metrics.annotations` has to be used so installation is needlessly verbose.
```sh
helm install node-problem-detector deliveryhero/node-problem-detector -n node-problem-detector --create-namespace \
--set metrics.enabled=true \
--set-string 'metrics.annotations.prometheus\.io/scrape=true' --set-string 'metrics.annotations.prometheus\.io/scheme=http'  --set-string 'metrics.annotations.prometheus\.io/port=20257' --set-string …
```
> node-problem-detector: Populate default Prometheus labels when metrics are enabled

- stable/cachet/Chart.yaml
- stable/cachet/README.md
- stable/cachet/templates/deployment.yaml
- stable/cachet/values.yaml
Adding values for podSecurityContext and securityContext for cachet Deployment
- [x ] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)
- [ x] I have read the [contribution instructions](https://github.com/deliveryhero/helm-charts#contributing), bumped chart version and regenerated the docs
> [stable/cachet] Add support of securityContext in cachet Deployment

- stable/cloudhealth-collector/Chart.yaml
- stable/cloudhealth-collector/README.md
- stable/cloudhealth-collector/templates/deployment.yaml
- stable/cloudhealth-collector/values.yaml
I wanted to pass an `api-token` secret from the aws secrets provider. It requires that I mount the volume with the secret, but unfortunately `cloudhealth-collector` doesn't support `extraVolumes` and `extraVolumeMounts`. That's why I decided to add this functionality. 
P.S. IMHO I think it would be very helpful to have it on every other helm chart as well :)
> [stable/cloudhealth-collector]: added extraVolumes + extraVolumeMounts options

- stable/killgrave/.helmignore
- stable/killgrave/Chart.yaml
- stable/killgrave/README.md
- stable/killgrave/example/imposters/example.imp.json
- stable/killgrave/templates/NOTES.txt
- stable/killgrave/templates/_helpers.tpl
- stable/killgrave/templates/configmap-imposters.yaml
- stable/killgrave/templates/configmap-schemas.yaml
- stable/killgrave/templates/deployment.yaml
- stable/killgrave/templates/hpa.yaml
- stable/killgrave/templates/ingress.yaml
- stable/killgrave/templates/service.yaml
- stable/killgrave/values.yaml
A chart to install [killgrave](https://github.com/friendsofgo/killgrave), a simulator for HTTP-based APIs.
Killgrave allows setting up a mock server with minimal preparation, this is especially useful when the actual implementation is not ready or in cases where you want to avoid hitting real services (ie. while load testing applications).
To mock endpoints, killgrave uses _imposters_ (a request-response pair). Imposters usually look like this:
```json
[
{
"request": {
"method": "GET",
"endpoint": "/gophers/01D8EMQ185CA8PRGE20DKZTGSR"            
},
"response": {
"status": 200,
"headers": {
"Content-Type": "application/json"
},
"body": "{\"data\":{\"type\":\"gophers\",\"id\":\"01D8EMQ185CA8PRGE20DKZTGSR\",\"attributes\":{\"name\":\"Zebediah\",\"color\":\"Purples\",\"age\":55}}}"
}
}
]
``` …
> [stable/killgrave] A helm chart to deploy an http mock server

- stable/kube-downscaler/Chart.yaml
- stable/kube-downscaler/README.md
- stable/kube-downscaler/templates/deployment.yaml
- stable/kube-downscaler/values.yaml
Do not override the default settings of kube-downscaler by default through the environment variables. I made a bone headed mistake which caused the chart to get deployed without removing the `DEFAULT_UPTIME` value in production and want to avoid this happening for others (or future me...).
> [stable/kube-downscaler] Do not override default config

- stable/killgrave/Chart.yaml
- stable/killgrave/README.md
- stable/killgrave/templates/deployment.yaml
- stable/killgrave/templates/hpa.yaml
- stable/killgrave/templates/ingress.yaml
- stable/killgrave/templates/service.yaml
- stable/killgrave/values.yaml
Corrections to killgrave's helm chart:
- Remove hardcoded port in ingress
- Correct type error when HPA is enabled
> [stable/killgrave] Remove hardcoded port from ingress.yaml

- stable/service-account/Chart.yaml
- stable/service-account/README.md
- stable/service-account/templates/clusterrole.yaml
- stable/service-account/templates/clusterrolebinding.yaml
Starting from 1.23 the RBAC APIs are no more in `beta`.
> [stable/service-account]: fix chart to fit 1.23+ k8s version

- stable/kube-downscaler/Chart.yaml
- stable/kube-downscaler/README.md
- stable/kube-downscaler/templates/clusterrole.yaml
added keda rules based on upstream project:
https://codeberg.org/hjacobs/kube-downscaler/src/branch/main/deploy/rbac.yaml
> [stable/kube-downscaler] sync cluster role with upstream for keda support

- stable/node-problem-detector/Chart.yaml
- stable/node-problem-detector/README.md
- stable/node-problem-detector/templates/daemonset.yaml
- stable/node-problem-detector/values.yaml
This adds support for image digests to the node-problem-detector chart.
> [stable/node-problem-detector] added support for image digests

- stable/backstage/Chart.yaml
- stable/backstage/README.md
- stable/backstage/templates/ingress.yaml
- stable/backstage/values.yaml
Currently, the parameter `ingressClassName` is missing.
> [stable/backstage] Missing ingressClassName parameter

- stable/k8s-event-logger/Chart.yaml
- stable/k8s-event-logger/README.md
- stable/k8s-event-logger/templates/deployment.yaml
- stable/k8s-event-logger/values.yaml
Added the ability to add securityContext and podSecurityContext to the deployment
> [stable/k8s-event-logger] Added securityContext and podSecurityContext

- stable/metabase/Chart.yaml
- stable/metabase/README.md
- stable/metabase/templates/deployment.yaml
- stable/metabase/values.yaml
This allows metabase to be used with sidecars, i.e. using Google SQL Auth Proxy to connect to an instance managed by GCP
- [ x] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)
- [ x] I have read the [contribution instructions](https://github.com/deliveryhero/helm-charts#opening-a-pr), bumped chart version and regenerated the docs
- [ x] Github actions are passing
> [stable/metabase] feat(metabase): add option to add extra containers

- stable/locust/Chart.yaml
- stable/locust/README.md
- stable/locust/templates/worker-pdb.yaml
- stable/locust/values.yaml
The labels on the `PodDisruptionBudget` were incorrect and did not match the actual pods. This causes the `cluster-autoscaler` to move the pods on node scale down with events like `deleting pod for node scale down`. And this interrupts running load tests.
> [stable/locust] fix labels for PodDisruptionBudget and enable for worker

- stable/cluster-overprovisioner/Chart.yaml
- stable/cluster-overprovisioner/README.md
- stable/cluster-overprovisioner/templates/deployments.yaml
- stable/cluster-overprovisioner/values.yaml
Update 'pause' to latest version. Switch to new official kubernetes
registry: https://kubernetes.io/blog/2022/11/28/registry-k8s-io-faster-cheaper-ga/
pause changelog at https://github.com/kubernetes/kubernetes/blob/v1.26.0/build/pause/CHANGELOG.md
> [stable/cluster-overprovisioner] pause 3.9

- stable/k8s-cloudwatch-adapter/Chart.yaml
- stable/k8s-cloudwatch-adapter/README.md
- stable/k8s-cloudwatch-adapter/templates/apiservice.yaml
- stable/k8s-cloudwatch-adapter/templates/crd.yaml
Even though the cloudwatch-adapter is already deprecated and archived it still works on K8s v1.22+, but the API resources need to be updated. This PR does just that, with the schema manually crafted from the docs.
> [stable/k8s-cloudwatch-adapter] Make compatible with K8s v1.22+

- stable/prometheus-k8s-events-exporter/Chart.yaml
- stable/prometheus-k8s-events-exporter/README.md
- stable/prometheus-k8s-events-exporter/templates/clusterrole.yaml
- stable/prometheus-k8s-events-exporter/templates/clusterrolebinding.yaml
The old RBAC API versions are removed, this makes sure the chart can handle both. ([ref](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22))
> [stable/prometheus-k8s-events-exporter] Add compatibility with K8s v1.22+

- stable/superset/Chart.yaml
- stable/superset/README.md
- stable/superset/templates/ingress.yaml
This pull request fixs removed API version from k8s v1.22.0.
> [stable/superset] Update superset api version compatiblity with v1.22.0

- stable/metabase/Chart.yaml
- stable/metabase/README.md
- stable/metabase/templates/ingress.yaml
- stable/metabase/values.yaml
* Make Metabase's ingress path type available as variable
> [stable/metabase]: Make Metabase's ingress path type available as variable

- stable/metabase/Chart.yaml
- stable/metabase/README.md
- stable/metabase/templates/ingress.yaml
- stable/metabase/values.yaml
The parameter `ingressClassName` is missing.
> [stable/metabase] Missing ingressClassName parameter

- stable/node-local-dns/Chart.yaml
- stable/node-local-dns/README.md
- stable/node-local-dns/templates/daemonset.yaml
- stable/node-local-dns/values.yaml
What: Add an `affinity` key to the node-local-dns daemonset file so that users can set which nodes the DNS pods run on. 
Why: We run AWS Fargate nodes in our EKS cluster which cannot successfully run node-local-dns pods.
> [stable/node-local-dns] feat: add affinity as templated value to node-local-dns chart

- stable/kube-downscaler/Chart.yaml
- stable/kube-downscaler/README.md
- stable/kube-downscaler/templates/deployment.yaml
Allow injecting more than one env variable into kube-downscaler environment variable.
> [stable/kube-downscaler] fix env variable injection

- stable/node-problem-detector/Chart.yaml
- stable/node-problem-detector/README.md
- stable/node-problem-detector/templates/daemonset.yaml
This is a small PR to change the /custom-config configmap volume mount from having 644 Unix permissions to 755. The advantage of this is that we can define custom scripts in the Helm chart, configure them in a custom plugin monitor and then have them executable by Node Problem Detector.
> [stable/node-problem-detector] change custom-config volume to have 755 permissions

- stable/k8s-cloudwatch-adapter/Chart.yaml
- stable/k8s-cloudwatch-adapter/README.md
- stable/k8s-cloudwatch-adapter/templates/apiservice.yaml
Release name is not always the same as the full name, but for the cross reference it is important that name used in the APIService spec is the same as the one used for the Service. Before this change, some configurations led to the metrics served by k8s-cloudwatch-adapter to not be available.
Refs: OGSYS-6125
> [stable/k8s-cloudwatch-adapter] Fix APIService reference

- stable/aws-service-quotas-exporter/Chart.yaml
- stable/aws-service-quotas-exporter/README.md
- stable/aws-service-quotas-exporter/values.yaml
- use named port for prom scrape config
> use named port for prom scape config

- stable/kube-bench/Chart.yaml
- stable/kube-bench/README.md
- stable/kube-bench/templates/_helpers.tpl
fixes #452
* add support for batch/v1 for Kubernetes v1.21+
> [stable/kube-bench] use batch/v1 for cronjobs on kubernetes >= 1.21

- stable/kube-bench/Chart.yaml
- stable/kube-bench/README.md
- stable/kube-bench/templates/_helpers.tpl
- stable/kube-bench/templates/cron.yaml
- stable/kube-bench/templates/serviceaccount.yaml
- stable/kube-bench/values.yaml
* bump kube-bench chart version to 0.1.7
* add aks support
* update cis benchmark for gke to 1.2.0
* update cis benchmark for eks to 1.1.0
* update kube-bench image to v0.6.12
* make volumes and volumeMounts configurable
* make jobname configurable to enable multiple deployments of the cronjob with different settings
* fix indent for container resources
* fix cronjob.command has no value if not overwritten by the deployment
* set backoffLimit to 0 to avoid reruns when kube-bench fails
* bump api chart version to v2
I would like to use this chart to deploy kube-bench into our AKS Cluster.
This required different volume mounts and a different benchmark.
```yaml
---
repositories:
- name: deliveryhero
url: https://charts.deliveryhero.io/
releases:
- name: kube-bench-aks
namespace: kube-bench …
```
> [stable/kube-bench] Update kube-bench image, code cleanup, aks support

- stable/locust/Chart.yaml
- stable/locust/README.md
- stable/locust/templates/worker-deployment.yaml
- stable/locust/values.yaml
Allow to configure nodeSelector, tolerations, affinity for worker explicitly.
It will be very useful where master is running using default node pool (so, no need to specify any toleration and affinity), but workers are needed to run on spot instances, which is in another node pool with specific taints. So, in that case, we need to configure only worker deployment
> [stable/locust] allow to configure nodeSelector, tolerations, affinity for worker explicitly

- stable/kube-bench/Chart.yaml
- stable/kube-bench/README.md
- stable/kube-bench/values.yaml
* bump kube-bench chart version to 0.1.8
* Upgrade kube-bench image to v0.6.13
> [stable/kube-bench] Update kube-bench image to 0.6.13

- stable/locust/Chart.yaml
- stable/locust/README.md
- stable/locust/templates/master-deployment.yaml
- stable/locust/templates/worker-deployment.yaml
Labels for the pods are not being correctly propagated, it is adding selector labels instead. (Note, locust.labels includes selector labels but also adds extra labels, as can be seen on helpers.tpl) 
```
{{- define "locust.labels" -}}
helm.sh/chart: {{ include "locust.chart" . }}
{{ include "locust.selectorLabels" . }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- range $key, $value := .Values.extraLabels }}
{{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
```
> [stable/locust]: Fixes locust extra labels on pods

- stable/kube-bench/Chart.yaml
- stable/kube-bench/README.md
- stable/kube-bench/values.yaml
* bump kube-bench chart version to 0.1.9
Update kube-bench image to 0.6.14
> [stable/kube-bench] Update kube-bench image to 0.6.14

- stable/kube-bench/Chart.yaml
- stable/kube-bench/README.md
- stable/kube-bench/templates/cron.yaml
- stable/kube-bench/values.yaml
So we can add specific labels to `kube-bench` pods and not only the deployment
> [stable/kube-bench] Add podLabels to kube-bench chart

- stable/node-local-dns/Chart.yaml
- stable/node-local-dns/README.md
- stable/node-local-dns/templates/configmap.yaml
- stable/node-local-dns/templates/daemonset.yaml
- stable/node-local-dns/values.yaml
Hello, here's a small change to allow overriding the `health` endpoint port in some cases where this port is already used by other components.
As an example, Kured is also using `8080` and thus `NodeLocal DNSCache` is failing :
```bash
listen tcp 169.254.20.20:8080: bind: address already in use
```
```bash
$> sudo netstat -nltp | grep 8080
tcp6       0      0 :::8080                 :::*                    LISTEN      3839/kured
```
The modification is currently running fine in one of our k8s clusters.
> [stable/node-local-dns] Allow health endpoint port override

- stable/kube-bench/Chart.yaml
- stable/kube-bench/README.md
- stable/kube-bench/values.yaml
* bump kube-bench chart version to 0.1.11
Update kube-bench image to 0.6.15
> [stable/kube-bench] Update kube-bench image to 0.6.15

- stable/node-local-dns/Chart.yaml
- stable/node-local-dns/README.md
- stable/node-local-dns/templates/servicemonitor.yaml
- stable/node-local-dns/values.yaml
Adding additional labels on ServiceMonitor to allow for customization experience
> [stable/node-local-dns] feat: add servicemonitor custom labels

- stable/node-local-dns/Chart.yaml
- stable/node-local-dns/README.md
- stable/node-local-dns/templates/configmap.yaml
- stable/node-local-dns/values.yaml
This will allow to specify protocol used for upstream communication. CoreDNS is sometimes tricky to adjust on Cloud Providers so it would be easier to specify it here as well. Especially current hardcoded value is tricky as in case if both force_tcp and prefer_udp options are specified the force_tcp takes precedence.
More info [here](https://coredns.io/plugins/forward/)
> [stable/node-local-dns] feat: Add option to specify protocol used for upstream

- stable/prometheus-spot-termination-exporter/Chart.yaml
- stable/prometheus-spot-termination-exporter/README.md
- stable/prometheus-spot-termination-exporter/templates/daemonset.yaml
Add extra labels support into spot termination exporter
> [stable/prometheus-spot-termination-exporter] Add extra labels support into spot termination exporter

- stable/kube-bench/Chart.yaml
- stable/kube-bench/README.md
- stable/kube-bench/values.yaml
* bump kube-bench chart version to 0.1.12
Update kube-bench image to 0.6.16
> [stable/kube-bench] Update kube-bench image to 0.6.16

- stable/kubecost-reports-exporter/Chart.yaml
- stable/kubecost-reports-exporter/README.md
- stable/kubecost-reports-exporter/values.yaml
> [stable/kubecost-reports-exporter] Update default parameters

- stable/gripmock/Chart.yaml
- stable/gripmock/README.md
- stable/gripmock/templates/ingress.yaml
- stable/gripmock/values.yaml
Allow exposing multiple ports in the ingress controller instead of the hardcoded 4770
> [stable/gripmock] allow exposing other ports than 4770

- stable/node-local-dns/Chart.yaml
- stable/node-local-dns/README.md
- stable/node-local-dns/templates/daemonset.yaml
- stable/node-local-dns/values.yaml
> stable/node-local-dns Extend daemonset arg list

- stable/node-local-dns/Chart.yaml
- stable/node-local-dns/README.md
- stable/node-local-dns/templates/daemonset.yaml
- stable/node-local-dns/values.yaml
Adding support for configuring custom DaemonSet Annotations and Labels and Pod Labels.
> [stable/node-local-dns] support podlabels and ds labels, annotations

- stable/node-problem-detector/Chart.yaml
- stable/node-problem-detector/README.md
- stable/node-problem-detector/templates/daemonset.yaml
- stable/node-problem-detector/values.yaml
The changes in this PR is to add support for defining volumeType of volume named `localtime` in node-problem-detector DaemonSet template. The default is set to `FileOrCreate`.
> [stable/node-problem-detector]: Adding support for defining volumeType of localtime

- stable/node-local-dns/Chart.yaml
- stable/node-local-dns/README.md
- stable/node-local-dns/templates/configmap.yaml
- stable/node-local-dns/templates/daemonset.yaml
- stable/node-local-dns/values.yaml
-  Return default configuration to be compatible  with iptables setup.
- add dnsServer to -localip only if setupIptables is true
- bind to dnsServer ip only if iptables setupIptables is true
- [v] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)
- [v] I have read the [contribution instructions](https://github.com/deliveryhero/helm-charts#opening-a-pr), bumped chart version and regenerated the docs
- [v] Github actions are passing
> [stable/node-local-dns] Changes for cilium local redirect support

- stable/prometheus-locust-exporter/Chart.yaml
- stable/prometheus-locust-exporter/README.md
- stable/prometheus-locust-exporter/templates/service-monitor.yaml
- stable/prometheus-locust-exporter/values.yaml
These changes allow to enable  metric relabelings with ServiceMonitor.
- [] Github actions are passing
> [stable/prometheus-locust-exporter] Add ability to use relablings with ServiceMonitor

- stable/node-problem-detector/Chart.yaml
- stable/node-problem-detector/README.md
- stable/node-problem-detector/values.yaml
Move the `additionalRelabelings` value to `serviceMonitor` where it should be
`additionalRelabelings` was added to be [used by the servicemonitor](https://github.com/deliveryhero/helm-charts/blob/master/stable/node-problem-detector/templates/servicemonitor.yaml#L35), and the value was misplaced under the wrong key.
This PR fixes that
> [stable/node-problem-detector]: additionalRelabelings value right place

- stable/node-problem-detector/Chart.yaml
- stable/node-problem-detector/README.md
- stable/node-problem-detector/templates/servicemonitor.yaml
- stable/node-problem-detector/values.yaml
Add `metricRelablings` to servicemonitor option
- Add optional value of type list to provide metricRelablings
- if metricRelablings provided, create the key and add the values
> [stable/node-problem-detector]: servicemonitor metricsRelablings

- stable/node-problem-detector/Chart.yaml
- stable/node-problem-detector/README.md
- stable/node-problem-detector/templates/serviceaccount.yaml
- stable/node-problem-detector/values.yaml
Adding annotation and label options to the service account in order to support IAM for Service Accounts in AWS.
> stable/node-problem-detector Adding annotation and label options to the service account

- stable/wiremock/Chart.yaml
- stable/wiremock/README.md
- stable/wiremock/templates/pdb.yaml
This PR removes the unrelated component label and name suffix from PDB template.
> [stable/wiremock] update PDB template

- stable/node-local-dns/Chart.yaml
- stable/node-local-dns/README.md
- stable/node-local-dns/templates/configmap.yaml
- stable/node-local-dns/values.yaml
Pushing the change from PR #508.
Apparently the original PR was based on an outdated branch, preventing the tests completion.
> [stable/node-local-dns]: feat(node-local-dns): add option to override coreDNS config

- stable/gripmock/Chart.yaml
- stable/gripmock/README.md
- stable/gripmock/templates/service.yaml
- stable/gripmock/values.yaml
This PR sets a variable for the gripmock service type to be able to use types of service like NodePort.
> [stable/gripmock] fix: add var to change the service type of gripmock

- README.md
- stable/toxiproxy/Chart.yaml
- stable/toxiproxy/README.md
- stable/toxiproxy/templates/ingress-frontend.yaml
- stable/toxiproxy/values.yaml
* Change from dockerhub hosted container repo to shopify-github repo
* Update toxi version to 2.7 (latest in shopify release at time)
* Change ingress-frontend to function like ingress(backend) as most of the apis in the if statement are on depreciated k8 versions
* Change values to match above changes
* Change values file node selector to default to linux / amd64 for mixed clusters.
> [stable/toxiproxy] ToxiProxy - Fixes for frontend ingress & container repo

- stable/field-exporter/.helmignore
- stable/field-exporter/Chart.yaml
- stable/field-exporter/README.md
- stable/field-exporter/crds/resourcefieldexport-crd.yaml
- stable/field-exporter/templates/_helpers.tpl
- stable/field-exporter/templates/deployment.yaml
- stable/field-exporter/templates/leader-election-rbac.yaml
- stable/field-exporter/templates/manager-rbac.yaml
- stable/field-exporter/templates/serviceaccount.yaml
- stable/field-exporter/values.yaml
A chart to install [field-exporter](https://github.com/deliveryhero/field-exporter). This controller is used to fill the gap in [k8s-config-connector](https://github.com/GoogleCloudPlatform/k8s-config-connector) for exporting value from Config Connector managed resources into Secrets and ConfigMaps.
> [stable/field-exporter]: field-exporter

- stable/k8s-event-logger/Chart.yaml
- stable/k8s-event-logger/README.md
- stable/k8s-event-logger/templates/deployment.yaml
- stable/k8s-event-logger/values.yaml
Made changes in deployment.yaml and values.yaml to add an option to change container name. Also set the default to "k8s-event-logger".
> [stable/k8s-event-logger] Added option to change container name

- README.md
- stable/field-exporter/Chart.yaml
- stable/field-exporter/README.md
- stable/field-exporter/templates/manager-rbac.yaml
- stable/field-exporter/values.yaml
- RBAC Permissions to manage secrets and config map
- Updated image version to v1.0.2
> [stable/field-exporter]: fixes rbac permissions and image version

- .github/CODEOWNERS
- stable/field-exporter/Chart.yaml
- stable/field-exporter/README.md
- stable/field-exporter/templates/deployment.yaml
- stable/field-exporter/templates/leader-election-rbac.yaml
- stable/field-exporter/templates/serviceaccount.yaml
- Add `deliveryhero/cloud-application-platform` to CODEOWNERS so they can review and merge PRs
- Add home/sources attributes to chart
- Remove hardcoded resource labels
> [stable/field-exporter] fix labels and more

- stable/kube-downscaler/Chart.yaml
- stable/kube-downscaler/README.md
Update kube-downscaler version to be able to manage Cronjobs in k8s>=1.25, after cronjob/v1beta1 removal. see the corresponding [issue](https://codeberg.org/hjacobs/kube-downscaler/issues/39)
> [stable/kube-downscaler] bump version to be k8s>=1.25 ready

- stable/cachet/Chart.yaml
- stable/cachet/README.md
- stable/cachet/templates/ingress.yaml
Without this configuration cert-manager cannot correctly generate certificate.
I've copied from `stable/hoppscotch` the snippet
[✔️] Title of the PR starts with chart name (e.g. [stable/mychartname])
[✔️] I have read the [contribution instructions](https://github.com/deliveryhero/helm-charts#opening-a-pr), bumped chart version and regenerated the docs
> [stable/cachet] ingress use tls key

- stable/field-exporter/Chart.yaml
- stable/field-exporter/README.md
- stable/field-exporter/values.yaml
New version includes the change to [Add info logs for successful status](https://github.com/deliveryhero/field-exporter/pull/23)
> [stable/field-exporter] version update

- stable/node-local-dns/Chart.yaml
- stable/node-local-dns/README.md
- stable/node-local-dns/templates/configmap.yaml
- stable/node-local-dns/templates/daemonset.yaml
- stable/node-local-dns/values.yaml
- Return customization of liveness probe port. It was deleted here https://github.com/deliveryhero/helm-charts/pull/510
> [stable/node-local-dns]: customize liveness probe port

- stable/cachet/Chart.yaml
- stable/cachet/README.md
- stable/cachet/templates/configmap.yaml
- stable/cachet/values.yaml
`DB_DRIVER` is being defined twice in the configmap, which makes helm fail with:
```
Helm upgrade failed: error while running post render on files: map[string]interface {}(nil): yaml: unmarshal errors:
line 28: mapping key "DB_DRIVER" already defined at line 19
```
Removed one of the properties and left the `env.public.DB_DRIVER`, which had the correct default value `pgsql`.
Version 1.3.3 only works if `env.public.DB_DRIVER` is defined as empty, so it's ignored and not set in the configmap.
> [stable/cachet] DB_DRIVER defined twice

- stable/kube-bench/Chart.yaml
- stable/kube-bench/README.md
- stable/kube-bench/values.yaml
* bump kube-bench chart version to 0.1.15
Update kube-bench image to 0.7.1
> [stable/kube-bench] Update kube-bench image to 0.7.1

- stable/node-local-dns/Chart.yaml
- stable/node-local-dns/README.md
- stable/node-local-dns/templates/configmap.yaml
I'm really sorry; in my previous [pull request](https://github.com/deliveryhero/helm-charts/pull/563) I didn't test the template rendering very well.
The result was wrong
`loopbind 169.254.20.25 172.20.0.10`
> [stable/node-local-dns]: Fix template rendering

- stable/k8s-resources/Chart.yaml
- stable/k8s-resources/README.md
- stable/k8s-resources/templates/hpa.yaml
**latest api version is v2 so I updated the hpa file.**
In my case sync failed because of this error:
`The Kubernetes API could not find version "v2beta1" of autoscaling/HorizontalPodAutoscaler for requested resource kube-system/k8s-resources-coredns-hpa. Version "v2" of autoscaling/HorizontalPodAutoscaler is installed on the destination cluster.`
**this PR will it.**
- [ X] Title of the PR starts with chart name (e.g. `[stable/mychartname]`)
- [ X] I have read the [contribution instructions](https://github.com/deliveryhero/helm-charts#opening-a-pr), bumped chart version and regenerated the docs
> [stable/k8s-resources] update hpa to latest v2 version

- stable/node-local-dns/Chart.yaml
- stable/node-local-dns/README.md
- stable/node-local-dns/templates/daemonset.yaml
- stable/node-local-dns/templates/service-upstream.yaml
- stable/node-local-dns/values.yaml
add option the set a custom Upstreamsvc 
if the custom upstreamsvc is set the upstream service is not created
> [stable/node-local-dns]: add option to set customUpstreamsvc

- README.md
`${PWD}` implies that the command could be run from any directory within the repo. This is not true since the path to `./ci/README.md.gotmpl` is relative.
> [stable/NONE]: update README, make helm-docs instructions robust

- stable/node-problem-detector/Chart.yaml
- stable/node-problem-detector/README.md
- stable/node-problem-detector/values.yaml
> [stable/node-problem-detector] update NPD chart to use version 0.8.18

- stable/locust/Chart.yaml
- stable/locust/README.md
- stable/locust/templates/extra-manifests.yaml
- stable/locust/values.yaml
This adds an easy way to deploy additional manifests alongside the locust chart like for example external secrets that can then be mounted into the locust pods via existing means (`environment_external_secret`)
> [stable/locust]: Add additional custom manifests

- stable/node-local-dns/Chart.yaml
- stable/node-local-dns/README.md
- stable/node-local-dns/templates/servicemonitor.yaml
- stable/node-local-dns/values.yaml
We are moving to prometheus operator monitoring but we need some extra configuration allowed by serviceMonitor like relabelings or metricsRelabelings. Unfortunately, it's not par of the chart yet.
I've included `path`, `honorLabels`, `interval`, `scrapeTimeout`, `metricRelabelings`, `relabelings`.
here an extra test.yaml to make sure it works
```yaml
serviceMonitor:
enabled: true
labels:
prometheus.io/operator: "true"
interval: 60s
scrapeTimeout: 90s
metricRelabelings:
- action: keep
regex: 'kube_(daemonset|deployment|pod|namespace|node|statefulset).+'
sourceLabels: [__name__]
relabelings:
- sourceLabels: [__meta_kubernetes_pod_node_name]
separator: ;
regex: ^(.*)$
targetLabel: nodename
replacement: $1
action: replace
```
> [stable/node-local-dns]: serviceMonitor endoints configuration not completed

- stable/prometheus-statsd-exporter/Chart.yaml
- stable/prometheus-statsd-exporter/README.md
- stable/prometheus-statsd-exporter/templates/servicemonitor.yaml
- stable/prometheus-statsd-exporter/values.yaml
This supports prometheus extension for service monitor CRD optionally.
> [stable/prometheus-statsd-exporter] add ServiceMonitor support for prometheus-statsd-exporter

- stable/prometheus-locust-exporter/Chart.yaml
- stable/prometheus-locust-exporter/README.md
- stable/prometheus-locust-exporter/templates/service-monitor.yaml
- stable/prometheus-locust-exporter/values.yaml
Service monitors for some Prometheus installation require specific labels and a bearer token to be picked up by the Prometheus scraper.
> [stable/prometheus-locust-exporter]: Additional Service Monitor Template Values

- stable/node-local-dns/Chart.yaml
- stable/node-local-dns/README.md
- stable/node-local-dns/templates/configmap.yaml
- stable/node-local-dns/values.yaml
add ability to enable [prefetch](https://coredns.io/plugins/cache/)
prefetch will prefetch popular items when they are about to be expunged from the cache. Popular means AMOUNT queries have been seen with no gaps of DURATION or more between them. DURATION defaults to 1m. Prefetching will happen when the TTL drops below PERCENTAGE, which defaults to 10%, or latest 1 second before TTL expiration. Values should be in the range [10%, 90%]. Note the percent sign is mandatory. PERCENTAGE is treated as an int.
> [stable/node-local-dns] add prefetch options to configuration

- stable/node-local-dns/Chart.yaml
- stable/node-local-dns/README.md
- stable/node-local-dns/templates/configmap.yaml
- stable/node-local-dns/values.yaml
https://jbn1233.medium.com/disable-coredns-aaaa-ipv6-query-response-a99ce9bc6dec
Many  k8s clusters operate on an internal network using only IPv4. The `no_ipv6_lookups` configuration option allows disabling IPv6 lookups, reducing the load and latency on CoreDNS servers.
> [stable/node-local-dns] add noIPv6Lookups config option

- .github/workflows/chart-testing.yml
- .github/workflows/check_pr.yaml
- .github/workflows/helm-conftest.yaml
- .github/workflows/helm-docs.yml
- .github/workflows/markdown-lint.yml
- .github/workflows/push-chart.yaml
Trying to fix this for https://github.com/deliveryhero/helm-charts/pull/589
> [stable/none] Update git actions

- stable/kube-bench/Chart.yaml
- stable/kube-bench/README.md
- stable/kube-bench/values.yaml
* bump kube-bench chart version to 0.1.16
Update kube-bench image to 0.8.0
> [stable/kube-bench] Update kube-bench image to 0.8.0

- stable/node-local-dns/Chart.yaml
- stable/node-local-dns/README.md
- stable/node-local-dns/templates/servicemonitor.yaml
> [stable/node-local-dns]: Use selector labels for ServiceMonitor selectors

- .github/workflows/helm-conftest.yaml
- ci/helm-conftest.sh
The image `instrumenta/helm-conftest` is super old and likely the root cause of the action be failing recently, this PR is trying to use alpine/helm and install conftest.
> [stable/none] fix: helm-conftest step

- stable/k8s-event-logger/Chart.yaml
- stable/k8s-event-logger/README.md
- stable/k8s-event-logger/templates/_helpers.tpl
- stable/k8s-event-logger/templates/clusterrole.yaml
- stable/k8s-event-logger/templates/clusterrolebinding.yaml
- stable/k8s-event-logger/templates/deployment.yaml
Enhance Helm Chart with Consistent Naming and Labeling Conventions
This pull request introduces several improvements to the Helm chart to ensure consistent naming and labeling across all Kubernetes resources. The changes include the addition of helper templates and the application of these templates in various resource definitions.
All templates now use the `k8s-event-logger.labels` helper. Name label is still used outside of the helper call
Source updated chart via this [PR](https://github.com/max-rocket-internet/k8s-event-logger/pull/47) with more context and details
```
diff new.yaml org.yaml
9c9
<     helm.sh/chart: k8s-event-logger-1.1.7
---
>     helm.sh/chart: k8s-event-logger-1.1.6
20c20
<     helm.sh/chart: k8s-event-logger-1.1.7
---
>     helm.sh/chart: k8s-event-logger-1.1.6 …
```
> [stable/k8s-event-logger]: Enhance Helm Chart with Consistent Naming and Labeling Conventions

- stable/node-problem-detector/Chart.yaml
- stable/node-problem-detector/README.md
- stable/node-problem-detector/values.yaml
Current AppVersion of node-problem-detector is v0.8.18, but a new version has been released a couple of months ago: https://github.com/kubernetes/node-problem-detector/releases/tag/v0.8.19
There is no need to update the manifests. Bumping the image is enough.
close #602
> [stable/node-problem-detector]: update NPD chart to use version v0.8.19

- stable/k8s-event-logger/Chart.yaml
- stable/k8s-event-logger/README.md
- stable/k8s-event-logger/templates/deployment.yaml
- stable/k8s-event-logger/values.yaml
Add missing args into values.yaml
`args` are showing up on original repo https://github.com/max-rocket-internet/k8s-event-logger/blob/master/chart/values.yaml#L15-L16
but not in helm charts
> [stable/k8s-event-logger]: add args to chart

- stable/wiremock/Chart.yaml
- stable/wiremock/README.md
- stable/wiremock/templates/deployment.yaml
- stable/wiremock/templates/serviceaccount.yaml
- stable/wiremock/values.yaml
This PR adds the capability of creating a service account resource with custom annotations for the wiremock consumer pod. 
Since we are using large stubs files for our mock tests and we are constantly updating those large files, it is the best solution for us to upload those files in to an s3 bucket and copy them to our wiremock consumer pod using an init container. To be able to this, we need some kind of authorization and authentication mechanism for our aws account. And using a service account for this suits us perfectly. Because of those reasons, related updates were made on the wiremock helm chart. All kinds of feedbacks are appreciated. Thanks in advance.
- serviceaccount.yaml is created
- template.spec.serviceAccount filed is added to deployment.yaml
- serviceAccount field is added …
> [stable/wiremock] Add serviceAccount

- stable/k8s-resources/Chart.yaml
- stable/k8s-resources/README.md
- stable/k8s-resources/ci/ct-values.yaml
- stable/k8s-resources/templates/clusterrole.yaml
- stable/k8s-resources/templates/clusterrolebinding.yaml
- stable/k8s-resources/values.yaml
Adding `ClusterRole` and `ClusterRoleBinding` resources support.
> [stable/k8s-resources]: support ClusterRoles and ClusterRoleBindings

- stable/k8s-resources/Chart.yaml
- stable/k8s-resources/README.md
- stable/k8s-resources/ci/ct-values.yaml
- stable/k8s-resources/templates/clusterrole.yaml
- stable/k8s-resources/templates/clusterrolebinding.yaml
- stable/k8s-resources/templates/configmap.yaml
- stable/k8s-resources/templates/cronjob.yaml
- stable/k8s-resources/templates/custom.yaml
- stable/k8s-resources/templates/hpa.yaml
- stable/k8s-resources/templates/ingress.yaml
- stable/k8s-resources/templates/namespace.yaml
- stable/k8s-resources/templates/priorityclass.yaml
- stable/k8s-resources/templates/scaledObject.yaml
- stable/k8s-resources/templates/secret.yaml
- stable/k8s-resources/templates/service.yaml
- stable/k8s-resources/templates/serviceaccount.yaml
In case when `values.yaml` is not static, but generated, using tools like [helmfile](https://github.com/helmfile/helmfile), or [KCL](https://www.kcl-lang.io) or any other. It's often needed to _dynamically enable / disable_ some resources based on certain conditions. For example using Helm like syntax 
```yaml
{{- $condition1 := .... -}}
{{- $condition2 := .... -}}
ServiceAccounts:
{{- if $condition1 }}
- fullnameOverride: sa1
annotations: 
foo: bar1
{{- end }}
{{- if $condition2 }}
- fullnameOverride: sa2
annotations: 
foo: bar2
{{- end }}
{{- if or $condition1 $condition2 }}
- fullnameOverride: sa3
annotations: 
foo: bar3
{{- end }
- fullnameOverride: sa4
annotations: 
foo: bar4
```
With this PR the above fragment could be rewritten like below, resulting in more readable and concise …
> [stable/k8s-resources]: introduce enabled flag

- stable/node-problem-detector/Chart.yaml
- stable/node-problem-detector/README.md
- stable/node-problem-detector/values.yaml
Current AppVersion of node-problem-detector is v0.8.19, but a new version has been released a couple of months ago: https://github.com/kubernetes/node-problem-detector/releases/tag/v0.8.20
An update in `settings.log_monitors` is required because of a refactoring in https://github.com/kubernetes/node-problem-detector/pull/955 
closes #620
> [stable/node-problem-detector]: update NPD chart to use v0.8.20

- stable/wiremock/Chart.yaml
- stable/wiremock/README.md
- stable/wiremock/templates/secret.yaml
- stable/wiremock/values.yaml
This PR implements environment secrets support for the chart.
> [stable/wiremock]: implements environment secrets support

- stable/locust/Chart.yaml
- stable/locust/README.md
- stable/locust/templates/master-deployment.yaml
- stable/locust/templates/master-service.yaml
- stable/locust/values.yaml
Updated the image version to the latest. Added in a fix for web-login argument. Adds ability to pass in a kubernetes attribute `loadBalancerIP` to the master service if it's type `LoadBalancer` so that you can attach a reserved IP to it if you wanted to.
> [stable/locust]: Updates locust version, adds fix for web-login, adds ability to pass reserved ip to load balancer service

- stable/locust/Chart.yaml
- stable/locust/README.md
- stable/locust/templates/master-deployment.yaml
- stable/locust/values.yaml
Updates master.auth.enabled to fix newer login method. Also updated to the latest tag
> [stable/locust]: Updates master.auth.enabled to fix newer login method

- stable/locust/Chart.yaml
- stable/locust/README.md
- stable/locust/templates/master-deployment.yaml
- stable/locust/templates/master-ingress.yaml
- stable/locust/templates/master-service.yaml
- stable/locust/values.yaml
Updates the service and ingress to accept more port configurability
> [stable/locust]: Updates the service and ingress to accept more port configurability

- stable/wiremock/Chart.yaml
- stable/wiremock/README.md
- stable/wiremock/templates/deployment.yaml
This PR fixes an issue with environment secrets handling where configured secrets have not been added to the env spec.
> [stable/wiremock] fix environment secrets handling

- stable/locust/Chart.yaml
- stable/locust/README.md
- stable/locust/templates/configmap-locust-lib.yaml
- stable/locust/templates/configmap-locust-locustfile.yaml
- stable/locust/values.yaml
Updates configmap for locustfile and lib to not be wrapped in explictstring "example"
> [stable/locust]: Updates configmap for locustfile and lib to not be wrapped in explictstring "example"

- stable/cluster-overprovisioner/Chart.yaml
- stable/cluster-overprovisioner/README.md
- stable/cluster-overprovisioner/templates/deployments.yaml
- stable/cluster-overprovisioner/values.yaml
Add terminationGracePeriodSeconds configuration option
> [stable/cluster-overprovisioner] add terminationGracePeriodSeconds

- stable/locust/Chart.yaml
- stable/locust/README.md
- stable/locust/templates/configmap-locust-lib.yaml
- stable/locust/templates/configmap-locust-locustfile.yaml
Updates the locustfile's configmap Files Glob syntax. Seems to be a small syntax change for helm 3 maybe.
> [stable/locust]: Updates locust chart configmap files glog statement

- .github/workflows/helm-publish.yaml
- stable/aws-ebs-csi-driver/Chart.yaml
- stable/aws-ebs-csi-driver/README.md
This is part of an effort to move away from chartmuseum
> Second try: host and update helm charts repo index.yaml on github

- stable/locust/Chart.yaml
- stable/locust/README.md
- stable/locust/templates/worker-keda.yaml
- stable/locust/values.yaml
Adding support for keda ScaledObject for additional scaling scenarios
> [stable/locust] Support Keda scaled object

- stable/node-local-dns/Chart.yaml
- stable/node-local-dns/README.md
- stable/node-local-dns/templates/daemonset.yaml
- stable/node-local-dns/values.yaml
Allow to change "tolerations" of the deamonset
> [stable/node-local-dns]: support modifying tolerations

- .github/workflows/helm-publish.yaml
- .gitignore
Resolves https://github.com/deliveryhero/helm-charts/issues/614
Goal: after chart changes are merged to `master` branch, we want to update [index.yaml](https://github.com/deliveryhero/helm-charts/blob/master/index.yaml) with the new chart versions.
How do we commit from a Github action to `master` branch? Problems:
- Job fails due to branch protection: https://github.com/deliveryhero/helm-charts/actions/runs/12371219728/job/34526841580#step:10:92
- Common problem: https://github.com/orgs/community/discussions/13836
> Update index.yaml from github actions after merge to master

- index.yaml
Part of ongoing work to move to hosting the entirety of this repo (Helm repo index.yaml and OCI packages) on Github.
To update this file I ran:
```shell
for d in stable/*; do helm package "$d" -u; done
yq eval -i '. |= .entries[][] |= .urls[0] = "oci://" + "ghcr.io/deliveryhero/helm-charts" + "/" + .name + ":" + .version' index.yaml
```
And then compared with:
```shell
helm search repo deliveryhero | grep -v private | grep -v NAME | sort > old.txt
helm repo add deliveryhero-oci https://raw.githubusercontent.com/deliveryhero/helm-charts/cc75ee73b8e434d9cc40a77fbad4cfe43f7dc259
helm search repo deliveryhero-oci | grep -v private | grep -v NAME | sort > new.txt
diff old.txt new.txt
```
Looks good. And templating a chart via the new `index.yaml` and OCI package works:
```shell
helm template …
```
> Updating index.yaml with OCI URLs

- .github/workflows/helm-publish.yaml
helm is expecting a legacy gpg keyring and gpg2 is using a new format `kbx`
> fix: Add legacy GPG keyring

- stable/node-problem-detector/Chart.yaml
- stable/node-problem-detector/README.md
- stable/node-problem-detector/templates/daemonset.yaml
- stable/node-problem-detector/values.yaml
Allows setting dnsPolicy for node problem detector. This is useful if users are using `hostNetwork: true` and are using checks that depend on their k8s dns setup (ex requires setting dnsPolicy to `ClusterFirstWithHostNet`)
The default value here is `ClusterFirst` (not `Default` ) - https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy
> [stable/node-problem-detector] allow setting dnsPolicy

- stable/node-local-dns/Chart.yaml
- stable/node-local-dns/README.md
- stable/node-local-dns/templates/daemonset.yaml
- stable/node-local-dns/values.yaml
Add initContainers to node-local-dns helm chart
> [stable/node-local-dns]: add support for initContainers

- stable/hoppscotch/Chart.yaml
- stable/hoppscotch/README.md
- stable/hoppscotch/templates/ingress.yaml
Changed ingress version to networking.k8s.io/v1
> [stable/hoppscotch] fix Ingress version

- stable/node-problem-detector/Chart.yaml
- stable/node-problem-detector/README.md
- stable/node-problem-detector/templates/daemonset.yaml
- stable/node-problem-detector/values.yaml
On clusters that runs both flatcar and ubuntu nodes pods are not starting properly because the host `/etc/localtime` location is a file on flatcar and a directory on ubuntu OS.
This PR adds an option to disable mounting the host localtime into the NPD daemonset. If timezone is UTC on the host, disabling this mounting will have no effect.
> [stable/node-problem-detector]: Add option to disable mounting host localtime volume

- .github/CODEOWNERS
Update codeowners to replace a no longer existent team.
Note to reviewer: Please also change the repo permission accordingly, removing `deliveryhero/gcp` and adding `deliveryhero/cloud-infrastructure` in it's place please.
> [stable/field-exporter] update codeowners

- stable/node-local-dns/Chart.yaml
- stable/node-local-dns/README.md
- stable/node-local-dns/templates/daemonset.yaml
- stable/node-local-dns/values.yaml
When custom config in node-local-dns is used, users may run the node-local-dns on a non-53 port. One use case is running node-local-dns on host network and using cilium to redirect traffic. In that case, running the node cache in a non-standard port can avoid potential conflict with any programs running on the host using port 53.
This commit adds a `port` to chart values. It defaults to 53 if not overridden. But providing this options gives users flexibility to run the service on a different port.
> [stable/node-local-dns] add `port` option to config

- stable/priority-class/Chart.yaml
- stable/priority-class/README.md
- stable/priority-class/templates/priorityclass.yaml
- stable/priority-class/values.yaml
This PR enhances the priority-class Helm chart to support optional fields preemptionPolicy, globalDefault, and custom description per priority class.
•	If `description` is not set, it defaults to "A high priority class to be used for important pods" (the previous static one).
•	`globalDefault` and `preemptionPolicy` are rendered only if explicitly defined in values.yaml (even if set to false).
•	Maintains backward compatibility for existing configurations.
> [stable/priority-class] feat: add support for preemptionPolicy and globalDefault in PriorityClass

- stable/prometheus-k8s-events-exporter/Chart.yaml
- stable/prometheus-k8s-events-exporter/README.md
- stable/prometheus-k8s-events-exporter/templates/deployment.yaml
Enables custom pod labeling for prometheus-k8s-events-exporter by linking the existing `extraLabels` configuration to the deployment pod template.
- Connected `extraLabels` from values.yaml to pod metadata labels in deployment.yaml
- Users can now add custom labels to pods via the `extraLabels` configuration
> [stable/prometheus-k8s-events-exporter] feat: enable pod labels via extraLabels in prometheus-k8s-events-exporter
